HW2: Ваксман Денис, M3339
itmo2019/task2 pull request #1
Opened 2019-03-08 01:59 UTC by DrDet

2019-03-14 18:08 UTC, trixartem requested changes

2019-03-14 18:08 UTC, trixartem commented on index.html
> +                            <time class="message-time">6 авг</time>
в атрибутах лучше указывать "машинное" время

2019-03-14 18:08 UTC, trixartem commented on index.html
> +                        <img class="avatar" width="30px" height="30px">
px можно не указывать. Для img рекомендуется всегда указывать атрибут alt. Если картинка декоративная, то alt должен быть пустой

2019-03-14 18:08 UTC, trixartem commented on main.css
> +    font-family: YandexSansBold;
Лучше добавлять фолбэк на системный шрифт

2019-03-14 18:08 UTC, trixartem commented on main.css
> +A, A:active, A:visited, A:hover {
селектор тегов пишется маленькими буквами

2019-03-14 18:08 UTC, trixartem commented on main.css
> +    font-family: YandexSanThin;
Можно свернуть в одно свойство

2019-03-14 18:08 UTC, trixartem commented on main.css
> +    color: #000000;
просто #000

2019-03-14 18:08 UTC, trixartem commented on main.css
> +#mail-box-actions {
Почему id,  а не классы?

2019-03-14 18:08 UTC, trixartem commented on main.css
> +    font-weight: normal;
по умолчанию normal - можно не указывать, если не хочется переопределить

2019-03-14 22:36 UTC, DrDet commented on main.css
> +#mail-box-actions {
Потому что это уникальный объект на странице. Зачем класс, которому принадлежит один объект?

2019-03-15 20:37 UTC, DrDet commented on main.css
> +#mail-box-actions {
Прочитал, что плохой тон, понял, исправил

2019-03-16 09:27 UTC, DrDet commented on main.css
> +#mail-box-actions {
Прочтиал, что плохой стиль. Исправил

2019-03-16 09:27 UTC, DrDet commented
Внес правки

2019-03-18 06:04 UTC, trixartem requested changes
Есть замечания по верстке:
- Макет не зависит от размеров окна
- Все сделано на абсолютах. Если контент поменяется, то элемненты будут наезжать друг на друга
- Если будет много текста в теле письма, то блока переклывает подвал

2019-03-18 06:04 UTC, trixartem commented on main.css
> +.top-search {
Блок поиска немного не похож на то что на макете

2019-03-18 06:04 UTC, trixartem commented on main.css
> +    position: absolute;
Т.е. все элементы внутри - absolute?

2019-03-18 06:04 UTC, trixartem commented on main.css
> +    background-image: url(//yastatic.net/mail/socialavatars/socialavatars/v4/ya-default.svg);
Картинка не загружается

2019-03-18 06:04 UTC, trixartem commented on index.html
> +                            <img class="moon" src="/static/moon.png" width="150" height="150" alt="">
Картинка тоже не работает. Не хватает атрибута alt

2019-03-18 06:04 UTC, trixartem commented on index.html
> +            <div class="inline ya-mail-logo"><span class="logo-ya">Яндекс</span><span class="logo-mail">Почта</span></div>
Логотип совсем не похож

2019-03-22 19:19 UTC, DrDet commented on index.html
> +                            <img class="moon" src="/static/moon.png" width="150" height="150" alt="">
а в чем может быть причина? Она вроде лежит файлом, как и остальные картинки

2019-03-22 19:54 UTC, DrDet commented
> Есть замечания по верстке:
> 
> * Макет не зависит от размеров окна
> * Все сделано на абсолютах. Если контент поменяется, то элемненты будут наезжать друг на друга
> * Если будет много текста в теле письма, то блока переклывает подвал

Исправил все замечания

2019-03-25 16:56 UTC, closed without merging