Виктори Ерохина, M3335
itmo2019/task2 pull request #11
Opened 2019-03-09 13:50 UTC by erokhinav

2019-03-13 12:01 UTC, underoot requested changes
В целом неплохо, но
* Необходимы правки по указанным замечаниям
* Необходимо сделать интерфейс адаптивным (учесть разные размеры экрана, на котором открывается сайт)
* Также стоит обратить внимания на требования, оглашенные в чате

2019-03-13 12:01 UTC, underoot commented on src/index.html
> +						<button class="first-message message-text message-box-button bold" tabindex="0">
Это заголовок письма, это не кнопка

2019-03-13 12:01 UTC, underoot commented on src/index.html
> +					<div class="checkbox-container"><div class="checkbox"></div></div>
_Checkbox_ должен быть инпутом с соответствующим типом

2019-03-13 12:01 UTC, underoot commented on src/index.html
> +			<img src="images/hamburger.svg" width="25px" height="25px">
Не критично, но при очень медленном интернете картинки имеют свойства загружаться после HTML-контента, причем в не которых случаях гораздо позже. Есть такая практика как делать _гамбургер_ с помощью одного лишь HTML. Преимуществом такого подхода является более плавный рендеринг

2019-03-13 12:01 UTC, underoot commented on src/index.html
> +		<div class="header-text"><span class="stretch"><span class="header-text-bold">Яндекс</span> Почта</span></div>
Не стоит привязываться в названиях классов к свойствам. Они могут в процессе эволюции интерфейса изменяться, например `header-text-bold` может стать уже не `bold`

2019-03-13 12:01 UTC, underoot commented on src/index.html
> +		<div class="header-text"><span class="stretch"><span class="header-text-bold">Яндекс</span> Почта</span></div>
Стоит использовать картинку для логотипа, а не трансформировать найденный Yandex Sans`

2019-03-13 12:01 UTC, underoot commented on src/index.html
> +	<link rel="stylesheet" href="fonts/yandex-font/stylesheet.css" type="text/css">
Стоит стили для шрифтов объявлять до любого их [использования в стилях](https://css-tricks.com/snippets/css/using-font-face/#article-header-id-0)

2019-03-13 12:01 UTC, underoot commented on src/index.html
> +						<div class="avatar"><div class="text-in-circle">Я</div></div>
Стоит учесть кейс когда аватарки нет

2019-03-13 12:01 UTC, underoot commented on src/index.html
> +			<button class="side-menu-button">Отправленные</button>
Не стоит забывать, что содержимое этих кнопок может быть любого размера

2019-03-13 12:01 UTC, underoot commented on src/css/styles.css
> +#incoming-button {
Кажется более семантичнее считать данные модификации относящимися к _активному_ разделу. Активным может быть не только раздел входящих

2019-03-13 12:01 UTC, underoot commented on src/css/styles.css
> +span.stretch {
Лучше картинкой без трансформаций

2019-03-13 12:01 UTC, underoot commented on src/css/styles.css
> +    display: inline-block;
Что-то с форматированием. Отступы прыгают

2019-03-13 12:01 UTC, underoot commented on src/css/styles.css
> +	list-style-type: none;
Стоит уточнить стиль и не применять ко всем непорядковым спискам

2019-03-13 12:01 UTC, underoot commented on src/css/styles.css
> +.side-menu button {
Лучше объединить с предыдущим селектором

2019-03-13 12:01 UTC, underoot commented on src/css/styles.css
> +	width: 590PX;
Стоит придерживаться единообразному стилю написания правил. Конечно верхний регистр парсер поймет, но читать будет сложнее человеком такой разный стиль.

2019-03-13 12:01 UTC, underoot commented on src/css/styles.css
> +	position: absolute;
Если это сделано только для позиционирования футера, то лучше сделать это через `position: relative`, поскольку `position: absolute` вовсе выдирает данный элемент из потока (_Flow_) документа

2019-03-13 12:01 UTC, underoot commented on src/css/styles.css
> +	-webkit-transform: scale(1,1.4);
Трансформаций лучше по возможности избегать, особенно что касается шрифтов

2019-03-13 12:01 UTC, underoot commented on src/css/styles.css
> +.bold {
Не стоит в качестве названий классов использовать свойства. Классы-хелперы редко, но бывают, но практически их единицы. Есть такая методология разработки стилей как _Функциональный CSS_, но стоит придерживаться единого стиля наименования классов все же и не миксовать их [стили]

2019-03-13 12:01 UTC, underoot commented on src/css/styles.css
> +.first-message:focus ~ .hidden-article {
В задании было сказано, что по клику на письмо оно открывается

2019-03-13 12:01 UTC, underoot commented on src/css/styles.css
> +p {
Лучше уточнить селектор.

2019-03-13 14:09 UTC, erokhinav commented on src/css/styles.css
> +.first-message:focus ~ .hidden-article {
А что не работает? У меня все ок: article открывается по клику на тему первого письма

2019-03-13 14:35 UTC, underoot commented on src/css/styles.css
> +.first-message:focus ~ .hidden-article {
При клике на автора письма — оно не открывается

2019-03-13 14:37 UTC, erokhinav commented on src/css/styles.css
> +#incoming-button {
Что имеется в виду под активным разделом?

2019-03-13 15:19 UTC, underoot commented on src/css/styles.css
> +#incoming-button {
Тому, который сейчас выбран. Скорее тут подразумевалась папка в почте, а не раздел

2019-03-14 21:12 UTC, erokhinav commented
Замечания исправлены.

2019-03-15 13:53 UTC, underoot commented on src/index.html
> +			<a id="compose-button">Написать</a>
Была же честная кнопка 😄

2019-03-15 13:55 UTC, underoot commented
У чекбоксов не отрисовано состояние "Выбрано". [Вот хорошее видео на эту тему](https://www.youtube.com/watch?v=E6kLaaQFctU)

2019-03-15 18:19 UTC, erokhinav commented on src/index.html
> +			<a id="compose-button">Написать</a>
В требованиях, оглашенных в чате, сказано, что все элементы управления должны быть ссылками. Получается, эти кнопки не относятся к элементам управления?

2019-03-15 18:21 UTC, erokhinav commented
Правильно ли я понимаю, что необходимо самостоятельно отдельно нарисовать дизайн чекбокса в состоянии "выбрано" и использовать его в вёрстке?

2019-03-16 08:59 UTC, erokhinav commented
Fixed

2019-03-16 09:59 UTC, underoot approved these changes

2019-03-16 11:53 UTC, closed without merging

2019-03-16 12:02 UTC, underoot commented on src/index.html
> +			<a id="compose-button">Написать</a>
Данная кнопка является кнопкой, потому что она не является переходом на следующий документ. По нажатию на нее происходит действие в рамках данной страницы (открывается интерфейс набора нового письма, к примеру). Ссылки являются элементами управления — элементами управления текущего адреса браузера

2019-03-16 12:06 UTC, erokhinav commented on src/index.html
> +			<a id="compose-button">Написать</a>
Логично, спасибо за пояснение!