Тельнов Сергей, M3334
itmo2019/task2 pull request #12
Opened 2019-03-09 13:55 UTC by SerTelnov

Сделал почту, но не успеваю добавить картинку и тест до вечера (понимаю что в этом суть :worried:). Честное слово завтра утром доделаю :angel: . Отправил что есть на данный момент, вдруг это считается как в дедлайн :sweat_smile:

2019-03-16 20:20 UTC, evgenymarkov requested changes
Проблемки с вертикальным центрированием практически везде, вёрстка совсем не тянется и вся рабочая область ограничена 800px в центре экрана.

2019-03-16 20:20 UTC, evgenymarkov commented on index.html
> +          <span>&#169; 2001&#150;2018, Яндекс</span>
Если есть Entity Name, то лучше вставлять их. Тогда `&#169;` -> `&copy;`, `&#150;` -> `&ndash;`

https://www.freeformatter.com/html-entities.html

2019-03-16 20:20 UTC, evgenymarkov commented on index.html
> +
В голом HTML, при отсутствии системы сборки, лишние пустые строки и пробелы могут привести к появлению визуальных искажений, неожиданных отступов. Убирать форматирование сейчас не призываю, просто имей в виду.

В React такой проблемы нет, как и в минифицированном HTML каким-нибудь вебпаком.

2019-03-16 20:20 UTC, evgenymarkov commented on index.html
> +    <button class="send_button">Написать</button>
У кнопки нет никакой реакции на нажатие и наведение курсора

2019-03-16 20:20 UTC, evgenymarkov commented on index.html
> +      <img class="square" src="./resources/images/service-menu.png">
Для логотипов и иконок SVG подходит лучше, можно вытянуть их с настоящей почты из DevTools либо найти похожие на [flat-icons](https://www.flaticon.com)

2019-03-16 20:20 UTC, evgenymarkov commented on index.html
> +        <span class="campany">Яндекс</span> <span class="service">Почта</span>
Опечатки в коде – неприятное явление если встретить его в действующем проекте

2019-03-16 20:20 UTC, evgenymarkov commented on index.html
> +    <div class="name">
Лучше подойдёт класс `logo` нежели `name`.

2019-03-16 20:20 UTC, evgenymarkov commented on index.html
> +        <span class="campany">Яндекс</span> <span class="service">Почта</span>
Это логотипы. Подставляя их текстом ты не сможешь достичь того же стиля, который задумывал дизайнер. Лучше всего в таких случаях подставлять картинки в формате SVG.

2019-03-16 20:20 UTC, evgenymarkov commented on index.html
> +  <div class="context">
Слишком абстрактное название класса. Не даёт никакой конкретики и представления о содержимом.

2019-03-16 20:20 UTC, evgenymarkov commented on index.html
> +      <div class="mails_bar">
Не bar, а скорее `actions`. Это действия над письмами. Соответственно каждое из них – `mail_action`.

2019-03-16 20:20 UTC, evgenymarkov commented on index.html
> +      <div class="mails_bar">
Элементы внутри этой строки не центрированы, а ещё это всё таки кнопки, но в разметке у  тебя `div`ы

2019-03-16 20:20 UTC, evgenymarkov commented on index.html
> +        <li class="mail" id="unread_mail">
id для стилизации лучше не использовать, навесь второй класс

2019-03-16 20:20 UTC, evgenymarkov commented on index.html
> +              <img class="oval-Ya" src="./resources/images/ya-logo.png">
Это не овал с Я, а логотип компании/аватар человека, поэтому такое имя класса плохо подходит

2019-03-16 20:20 UTC, evgenymarkov commented on styles.css
> +  width: 800px;
В задании подразумевалось, что почта должна выглядеть хорошо хотя бы на всех десктопах. Поэтому ограничение в 800px не подходит.

2019-03-16 20:20 UTC, evgenymarkov commented on styles.css
> +a {
Разлепляй селекторы хотя бы одной пустой строкой

2019-03-16 20:20 UTC, evgenymarkov commented on styles.css
> +  color: #000000;
Можно сократить до `#000`, как и `#ffffff` до `#fff`

2019-03-16 20:20 UTC, evgenymarkov commented on styles.css
> +#article_checkbox {
Для стилизации лучше использовать только классы, id вообще противопоказаны, а селекторы по тэгу нужны раз в сто лет чтобы глобально обнулить какие-нибудь margin'ы/padding'и для body.

2019-03-16 20:20 UTC, evgenymarkov commented on styles.css
> +  top: 8.5px;
Остерегайся дробных значений пикселей. Браузеры по разному интерпретируют их и могут появиться неожиданные артефакты.

2019-03-18 22:10 UTC, SerTelnov commented on styles.css
> +#article_checkbox {
В данном случае ```id``` нужен чтобы ```label``` ссылался на него, с ```class```'ом у меня провернуть такой же трюк не получилось..
В остальных местах поправил

2019-03-18 22:12 UTC, SerTelnov commented
/fixed 
логотип поменял просто на украденный ```img```, ```cvg``` в интернете такой не нашел, думал взять прям прям с сайта, но решил что это уже перебор и убрал
про ```id``` для checkbox написал в комментарии на замечание.

2019-03-19 07:37 UTC, evgenymarkov commented
![image](https://user-images.githubusercontent.com/16443248/54588036-9f74b180-4a43-11e9-9342-06f5130839fa.png)
Проблемы с вертикальным центрированием остались

2019-03-19 07:37 UTC, evgenymarkov commented
![image](https://user-images.githubusercontent.com/16443248/54588067-b9ae8f80-4a43-11e9-8525-3d00295c2428.png)
Очень маленькие отступы

2019-03-19 07:37 UTC, evgenymarkov commented
Типографика очень сильно отличается от макета

2019-03-19 07:40 UTC, evgenymarkov approved these changes
Всё таки используй классы для стилизации элементов, а селекторы по HTML тэгам/ по id так редко как это возможно.

Остальные замечания можно в рамках третьей домашки поправить)

2019-03-19 07:40 UTC, closed without merging