Хусаинов Анвер
itmo2019/task2 pull request #13
Opened 2019-03-09 14:00 UTC by AnverK

2019-03-18 05:31 UTC, trixartem requested changes
Молодец, что предусмотрел длинные тексты и адаптивность окна.
Если в текст письма добавить много контента, то крестик закрытия скролится вместе с контентом, а должен быть всегда сверху и не сролится.
Есть некоторые замечания по коду и нельзя использовать JS

2019-03-18 05:31 UTC, trixartem commented on .idea/inspectionProfiles/Project_Default.xml
> +<component name="InspectionProjectProfileManager">
Можно этот файл добавить в .gitignore и тогда он не будет попадать в PR

2019-03-18 05:31 UTC, trixartem commented on fonts/HelveticaNeue/example.html
> +<!DOCTYPE html>
Этот файлик тоже не нужен

2019-03-18 05:31 UTC, trixartem commented on bem/common.blocks/yandex-mail/yandex-mail.css
> +    position: absolute;
А для чего делать  body absolute?

2019-03-18 05:31 UTC, trixartem commented on bem/common.blocks/yandex-mail/__main-menu/yandex-mail__main-menu.css
> +    position: absolute;
Везде использовать absolute не очень хорошо. Потому что если надо будет сделать так, что бы контент переносился и влиял на размеры родителя и окружающих блоков, то прийдет переделывать всю верстку

2019-03-18 05:31 UTC, trixartem commented on fonts/HelveticaNeue/style.css
> +font-family: 'HelveticaNeueCyr-Bold';
Можно задать одно название, а для жирности указывать только font-weight. У тебя же правильно описывается yandex sans

2019-03-18 05:31 UTC, trixartem commented on bem/common.blocks/yandex-mail/__mail-frame/yandex-mail__mail-frame.css
> +    background-color: #ffffff;
Можно просто #fff

2019-03-18 05:31 UTC, trixartem commented on bem/common.blocks/text/_font/text_font_helvetica.css
> +.text_font_helvetica {
Такие классы лучше не составлять. Если у текста будет много разных свойст(жирный, наклонный, 19-го размера), то это будут длинные и сложные классы.
Классы луше группировать по блокам, а шрифт вообще наследуется.
Например есть блока письма
```
mail
  mail__header
  mail__body
    mail__text //Здесь можно указывать все стили свзянные с текстом, которые изменяются относительно родителя
    mail__date
  mail__footer
```

2019-03-18 05:31 UTC, trixartem commented on bem/common.blocks/text/_font-size/text_font-size_13.css
> +    font-size: 13px;
Размер тоже лучше указывать в конкретных блоках

2019-03-18 05:31 UTC, trixartem commented on bem/common.blocks/search-box/search-box.css
> +    font-family: 'Yandex Sans Text', serif;
font-size, font-family можно указывать в одном свойстве

2019-03-18 05:31 UTC, trixartem commented on bem/common.blocks/search-box/search-box.css
> +.search-box {
Этот блок не очень похож на тот, что в макете

2019-03-18 05:31 UTC, trixartem commented on bem/common.blocks/message/_unread.css
> +.message_unread {
Пустой файл - можно убрать

2019-03-18 05:31 UTC, trixartem commented on bem/common.blocks/message/__unread-dot/message__unread-dot.css
> +.message__unread-dot {
Можно сделать псевдо-элементом

2019-03-18 05:31 UTC, trixartem commented on bem/common.blocks/main-menu/__item/main-menu__item.css
> +    padding-left: 10px;
можно в одно свойство - padding

2019-03-18 05:31 UTC, trixartem commented on bem/common.blocks/main-logo/main-logo.css
> +}
тоже можно убрать

2019-03-18 05:31 UTC, trixartem commented on bem/common.blocks/mail-box/__animation/mail-box__animation_remove-message.js
> +setRemoveListener();
Js? Но ведь его нельзя, пока. использовать

2019-03-21 13:58 UTC, AnverK commented on bem/common.blocks/message/__unread-dot/message__unread-dot.css
> +.message__unread-dot {
А зачем?

2019-03-21 14:17 UTC, AnverK commented on bem/common.blocks/yandex-mail/__main-menu/yandex-mail__main-menu.css
> +    position: absolute;
Не очень понятно тогда, в каких случаях можно использовать absolute. В любом случае, если изменятся размеры блока с position: absolute, придётся переделывать всю вёрстку. Правильно ли я понимаю, что стоит использовать absolute только для позиционирования элементов блока, а соответствующие блоки делать relative?

2019-03-21 14:26 UTC, AnverK commented
> Если в текст письма добавить много контента, то крестик закрытия скролится вместе с контентом, а должен быть всегда сверху и не сролится.

Правда ли, что sticky не стоит использовать, так как его поддерживает около 90% бразуеров?
https://caniuse.com/#search=sticky

2019-03-25 17:21 UTC, trixartem commented
sticky можно использовать, если нет этих 10% браузеров)

2019-03-25 17:22 UTC, trixartem commented
Задание принято.

2019-03-25 17:22 UTC, closed without merging