Курышев Василий
itmo2019/task2 pull request #14
Opened 2019-03-09 14:00 UTC by VaSillii

Task-2

2019-03-13 07:33 UTC, mokhov requested changes
В целом мне почти всё понравилось в вёрстке за ислючением шрифтов. По CSS тоже. Нужно внедрить небольшие доработки и будет кул!

2019-03-13 07:33 UTC, mokhov commented on css/style.css
> +    font-family: YandexSansBold;
https://css-tricks.com/snippets/css/using-font-face/

2019-03-13 07:33 UTC, mokhov commented on css/style.css
> +    margin: 0;
В первой лекции я рассказывал почему лучше никогда не пользоваться универсальным селектором. Т.е лучше всегда сбрасывать стили непосредственно у элемента.

2019-03-13 07:33 UTC, mokhov commented on css/style.css
> +    background-color: #000000;
`000000` -> `000`

2019-03-13 07:33 UTC, mokhov commented on css/style.css
> +    width: calc(100% - 50px);
Почему здесь нужен именно calc?

2019-03-13 07:33 UTC, mokhov commented on css/style.css
> +::-webkit-input-placeholder {
И несмотря на это в input'е у меня всё равно Times
![Почта 2019-03-13 10-28-48](https://user-images.githubusercontent.com/357689/54260720-ced67a80-457a-11e9-8800-bdacd73eb8ec.jpg)

2019-03-13 07:33 UTC, mokhov commented on css/style.css
> +    font-family: "HelveticaNeue", sans-serif;;
Можно объединить эти стили в одном правиле

2019-03-13 07:33 UTC, mokhov commented on index.html
> +                            <div class="logo-yandex"><img src="img/2-layers.png" alt="Yandex"></div>
Это логотип компании, отправившей письмо, его так же может и не быть

2019-03-13 07:33 UTC, mokhov commented on index.html
> +                            <div class="blue-circle"></div>
Это не синий круг :-D А маркер прочитанности письма

2019-03-13 07:33 UTC, mokhov commented on index.html
> +                    <li>
Сейчас при наведении на пункт обводка появляется на всю ширину, но кликабельная только область текста, это не совсем корректно и хочется это поправить

2019-03-13 07:57 UTC, mokhov commented
`<perfect mode="on">`
1. Когда ты делаешь ховеры, то всегда нужно думать над понятно ли отозвался интерфейс, видно ли пользователю действие. Сейчас на ссылках «Переслать» и прочих еле заметное подчёркивание, например.
2. В идеале пиксель перфект – это когда макет накладывают на вёрстку и они не отличимы, сейчас даже невооруженным глазом видно иногда, что размеры не те
![Image 2019-03-13 10-54-06](https://user-images.githubusercontent.com/357689/54262090-6c7f7900-457e-11e9-8bce-261246f7389a.jpg)
3. Много пунктов меню выглядит вот так и я уверен что ограничение минимальной ширины сделано под них
![Почта 2019-03-13 10-56-14](https://user-images.githubusercontent.com/357689/54262197-a94b7000-457e-11e9-916b-9bca2c18a131.jpg)
4. Если в одном пункте много текста, то всё тоже едет
![Почта 2019-03-13 10-56-57](https://user-images.githubusercontent.com/357689/54262227-bff1c700-457e-11e9-8026-7d71b16a4016.jpg)
Глобально нужно всегда полагаться на «здесь может быть не этот текст, а другой»
`<perfect mode="off">`

2019-03-21 15:17 UTC, mokhov commented
Дизайнеры не всегда рисуют состояния, но если этого нет, то всё равно плохо делать просто ховер, нужно явно реагировать. Вот пример, изначально то как сделано у тебя, а далее я добавил изменение цвета. Ощущение разное
![screencast 2019-03-21 18-13-35](https://user-images.githubusercontent.com/357689/54762616-7c91fb00-4c05-11e9-8946-b243e4c4274d.gif)

2019-03-21 15:18 UTC, mokhov commented on css/content.css
> +    width: calc(100% - 169px);
calc это почти всегда плохо

2019-03-21 15:18 UTC, mokhov commented on css/content.css
> +    margin-left: 3.7%;
Почему именно такой отступ?

2019-03-21 15:18 UTC, closed without merging

2019-03-21 19:52 UTC, VaSillii commented on css/content.css
> +    margin-left: 3.7%;
Я его с исходя из макета высчитывал.

2019-03-21 19:52 UTC, VaSillii commented on css/content.css
> +    width: calc(100% - 169px);
Те лучше задавать размеры в процентном соотношении?