Влад Сайфулин, M3337
itmo2019/task2 pull request #16
Opened 2019-03-09 16:20 UTC by Recognized

2019-03-15 12:19 UTC, evgenymarkov requested changes

2019-03-15 12:19 UTC, evgenymarkov commented on .idea/encodings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Файлы настроек IDE лучше не хранить в репозитории. Они зачастую специфичны для конкретного разработчика. Чтобы проблему решить сделать нужно следующее:

1) Добавить `.idea/` в `.gitignore`
2) Удалить из индекса git (но не с файловой системы) директорию `.idea`.
3) Сделать коммит с удалением файлов и запушить его.

2019-03-15 12:19 UTC, evgenymarkov commented on mail.html
> +<!DOCTYPE html>
Файл с разметкой главной страницы проекта принято называть `index.html`. Этому соглашению следуют и веб-серверы, которые при обращении, к примеру, на `/`, пытаются найти `/index.html` в файловой системе.

2019-03-15 12:19 UTC, evgenymarkov commented on mail.html
> +<body class="mail_body">
Нижнее подчёркивание обычно не используют в названиях блоков, вместо него слова отделяются через -. Хорошие практики нейминга можно подсмотреть [здесь](https://ru.bem.info/methodology/css/#Именование).

2019-03-15 12:19 UTC, evgenymarkov commented on mail.html
> +                    <svg height="3rem" id="svgicon-boot--Mail_ru" viewBox="0 0 54 32"
Кажется id здесь лишний

2019-03-15 12:19 UTC, evgenymarkov commented on mail.html
> +                    <svg fill="currentColor" fill-rule="nonzero" viewBox="0 0 75 32" height="3rem" xmlns="http://www.w3.org/2000/svg">
Отлично, логотипы в SVG) Единственный минус инлайновых SVG – они не кэшируются браузерами.

2019-03-15 12:19 UTC, evgenymarkov commented on mail.html
> +                    <svg fill="currentColor" fill-rule="nonzero" viewBox="0 0 75 32" height="3rem" xmlns="http://www.w3.org/2000/svg">
Подробнее о способах подключения svg можно почитать здесь

https://css-tricks.com/using-svg/

2019-03-15 12:19 UTC, evgenymarkov commented on mail.html
> +                    <svg fill="currentColor" fill-rule="nonzero" viewBox="0 0 75 32" height="3rem" xmlns="http://www.w3.org/2000/svg">
Вкратце опишу тут

Способы подключения SVG:

1) В CSS указать `url('url картинки или путь до файла')`
2) Подключить через `<img src="..." />`
3) Подключить через object: `<object type="image/svg+xml" data="url или путь до файла"> </object>`
4) Вставить в HTML как есть: `<body> <svg ...> ... </svg> </body>`

4 способ хорош, можно стилизовать и мучать эту svg'шку как душе угодно.

Но минус в том, что если SVG занимает, к примеру, 5 килобайт, то ты всегда эти 5 килобайт будешь загружать, потому что это часть разметки. Но если тебе не нужна гибкость, а просто векторная картинка, которая всегда одна и та же, а логотип таковой и является, то лучше подключить через 1, 2 или 3 способ и тогда браузер единожды загрузит эту картинку, а потом будет брать из кэша.

2019-03-15 12:19 UTC, evgenymarkov commented on mail.html
> +                <p><a class="link_unset_style single-line letters_panel_link" href="#">Переслать</a></p>
В идеале это должны быть честные `<button>` и без лишних обёрток, но фиксить сейчас не призываю

2019-03-15 12:19 UTC, evgenymarkov commented on mail.html
> +        <div class="letters_inline_first_task" id="first_task">
id лучше не использовать за исключением тех случаев, когда элемент действительно уникален на странице и к нему нужно обратиться из JavaScript

2019-03-15 12:19 UTC, evgenymarkov commented on css/index.css
> +    richness: 80;
В спецификации этих двух свойств (voice-family, richness) нет

2019-03-15 12:19 UTC, evgenymarkov commented on css/mail.css
> +    position: relative;
Правило ни на что не влияет

2019-03-15 12:19 UTC, evgenymarkov commented on css/mail.css
> +    margin: 0 0 0 calc(12rem + 22px);
Комбинирование rem и px во всём коде не обосновано. rem у тебя считается от базового размера шрифта, который зачастую в браузерах равен 16px.

2019-03-15 13:25 UTC, Recognized commented on mail.html
> +        <div class="letters_inline_first_task" id="first_task">
это все осталось от версии с джаваскриптом, сейчас не используется

2019-03-15 13:43 UTC, Recognized commented on mail.html
> +<body class="mail_body">
я пофикшу наименования в рамках следующего дз

2019-03-15 18:58 UTC, Recognized commented on .idea/encodings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Удалил

2019-03-15 18:59 UTC, Recognized commented on mail.html
> +<!DOCTYPE html>
Переименовал

2019-03-15 18:59 UTC, Recognized commented on mail.html
> +                    <svg height="3rem" id="svgicon-boot--Mail_ru" viewBox="0 0 54 32"
Fixed

2019-03-15 19:00 UTC, Recognized commented on mail.html
> +                    <svg fill="currentColor" fill-rule="nonzero" viewBox="0 0 75 32" height="3rem" xmlns="http://www.w3.org/2000/svg">
Вынес в отдельные файлы в images/

2019-03-15 19:01 UTC, Recognized commented on css/mail.css
> +    margin: 0 0 0 calc(12rem + 22px);
Перевел все в px, думал при зуме браузера меняется размер базового шрифта, но нет

2019-03-19 07:30 UTC, evgenymarkov approved these changes

2019-03-19 07:30 UTC, closed without merging