Глухов Евгений, M3337
itmo2019/task2 pull request #17
Opened 2019-03-09 16:33 UTC by AntiFrizz1

2019-03-13 13:22 UTC, rmbaad requested changes

2019-03-13 13:22 UTC, rmbaad commented on styles/style.css
> +    width: 800px;
Должно тянуться на ширину окна. Это одно из условий задания

2019-03-13 13:22 UTC, rmbaad commented on styles/style.css
> +.page {
Нет вообще шрифтов. Должен быть Yandex Sans

2019-03-13 13:22 UTC, rmbaad commented on styles/style.css
> +.logo {
Лого совсем не похоже на то что в макете

2019-03-13 13:22 UTC, rmbaad commented on styles/style.css
> +    float: left;
Можно без флоатов, флоаты для обтекания текста. Посмотри на inline-block

2019-03-13 13:22 UTC, rmbaad commented on index.html
> +            <div class="search-text">Поиск</div>
И как сюда что-то написать?) это должен быть input

2019-03-13 13:22 UTC, rmbaad commented on styles/style.css
> +    float: left;
И здесь без флоата надо

2019-03-13 13:22 UTC, rmbaad commented on styles/style.css
> +.first {
Зачем пустой?

2019-03-13 13:22 UTC, rmbaad commented on styles/style.css
> +.third {
Все три полоски можно было сделать одним классом

2019-03-13 13:22 UTC, rmbaad commented on styles/style.css
> +    float: left;
И тут флоат не нужен

2019-03-13 13:22 UTC, rmbaad commented on styles/style.css
> +    height: 2.4px;
Из-за такой высоты криво выглядит. Пиксели не могут быть дробными

2019-03-13 13:22 UTC, rmbaad commented on styles/style.css
> +    opacity: 0.5;
Текст внутри блока тоже будет прозрачным, а тогда его будет очень плохо видно и в макете не так

2019-03-13 13:22 UTC, rmbaad commented on styles/style.css
> +    font-stretch: normal;
Зачем эти стили везде дублируются?

2019-03-13 13:22 UTC, rmbaad commented on index.html
> +                        <div class="write-text">Написать</div>
Это должна быть кнопка

2019-03-13 13:22 UTC, rmbaad commented on styles/style.css
> +.inbox {
Выделение не у входящих а у выбранного пункта. Т.е. должен быть класс, который можно навесить на любой пункт и получить его выделенным

2019-03-13 13:22 UTC, rmbaad commented on styles/style.css
> +    font-style: normal;
Откуда взялись эти стили?

2019-03-13 13:22 UTC, rmbaad commented on styles/style.css
> +.my-checkbox:checked {
Ты конечно молодец, что реализовал свой чекбокс) но можно было обойтись стандартным

2019-03-13 13:22 UTC, rmbaad commented on styles/style.css
> +    width: auto;
Эти оба свойства ничего не делают тут

2019-03-13 13:22 UTC, rmbaad commented on styles/style.css
> +    float: left;
Можно инлайн-блоками. Флоаты для обтекания текста

2019-03-13 13:22 UTC, rmbaad commented on styles/style.css
> +    border: solid 0.5px #e2e2e2;
Не надо делать дробные пиксели. Здесь достаточно однопиксельной рамки без фона

2019-03-13 13:22 UTC, rmbaad commented on styles/style.css
> +    float: left;
Зачем float и clear?

2019-03-13 13:22 UTC, rmbaad commented on styles/style.css
> +    float: left;
Что тут делает float? Кажется он не нужен

2019-03-13 13:22 UTC, rmbaad commented on styles/style.css
> +.footer-menu-button {
Это не кнопки

2019-03-13 13:22 UTC, rmbaad commented on styles/style.css
> +    height: auto;
Лишние свойства

2019-03-13 13:22 UTC, rmbaad commented on styles/style.css
> +.simple-line {
Тоже можно просто сделать бордером футера

2019-03-13 13:22 UTC, rmbaad commented on styles/style.css
> +    float: left;
Зачем тут float left? Блок же и так инлайн

2019-03-13 13:22 UTC, rmbaad commented on styles/style.css
> +    float: left;
Не стоит переопределять правила глобально для тега

2019-03-15 20:02 UTC, AntiFrizz1 commented on styles/style.css
> +.my-checkbox:checked {
Но стандартные чекбоксы по-разному. И кажется это не очень круто. Плюс они не похожи на то что было в задании.

2019-03-15 20:02 UTC, AntiFrizz1 commented on styles/style.css
> +.my-checkbox:checked {
*по-разному отображаются в разных браузерах

2019-03-15 20:03 UTC, AntiFrizz1 commented on styles/style.css
> +    float: left;
То есть нужно переделать на inline-block?

2019-03-16 16:44 UTC, AntiFrizz1 commented
@rmbaad Исправил

2019-03-18 08:50 UTC, rmbaad requested changes
Т.к. по заданию нужно чтобы вёрстка не ломалась от количества контента, нужно сделать одну правку, в остальном всё ок

2019-03-18 08:50 UTC, rmbaad commented on styles/style.css
> +    position: absolute;
Благодаря такому подходу, если писем будет больше — футер будет на них налезать и перекрывать. На самом деле можно обернуть письма в отдельный блок с min-height, после него добавить футер и всё будет ок

2019-03-18 17:11 UTC, AntiFrizz1 commented
@rmbaad Исправил

2019-03-19 10:45 UTC, rmbaad approved these changes

2019-03-19 10:46 UTC, closed without merging