Ионов Дмитрий, M3337
itmo2019/task2 pull request #18
Opened 2019-03-09 16:39 UTC by RuzikHan

2019-03-15 19:38 UTC, evgenymarkov requested changes
Слишком много списков. Применил их и к месту и не к месту.
Именование классов по БЭМу можно оставить на следующую домашку

https://ru.bem.info/methodology/naming-convention/#правила-формирования-имен

2019-03-15 19:38 UTC, evgenymarkov commented on src/.idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Файлы настроек IDE лучше не хранить в репозитории. Они зачастую специфичны для конкретного разработчика. Чтобы проблему решить сделать нужно следующее:

1) Добавить `.idea/` в `.gitignore`
2) Удалить из индекса git (но не с файловой системы) директорию `.idea`.
3) Сделать коммит с удалением файлов и запушить его.

2019-03-15 19:38 UTC, evgenymarkov commented on src/index.html
> +<html lang="en">
Документ содержит, по большей степени, контент на русском языке, поэтому и `lang="ru"` должен быть

2019-03-15 19:38 UTC, evgenymarkov commented on src/index.html
> +    <link rel="stylesheet" href="style.css">
Есть [рекомендованный порядок элементов](https://stackoverflow.com/a/26505680) в head и лучше ему следовать.

2019-03-15 19:38 UTC, evgenymarkov commented on src/index.html
> +        <div class="description"><label class="yandex">Яндекс</label> Почта</div>
`h1`, а не `div`

2019-03-15 19:38 UTC, evgenymarkov commented on src/index.html
> +        <div class="ln ln1"></div>
Лучше использовать SVG иконки, чем пытаться с помощью CSS повторить те или иные фигуры.

Подробнее о способах подключения svg можно почитать здесь
https://css-tricks.com/using-svg/

Вкратце опишу тут

Способы подключения SVG:

1) В CSS указать `url('url картинки или путь до файла')`
2) Подключить через `<img src="..." />`
3) Подключить через object: `<object type="image/svg+xml" data="url или путь до файла"> </object>`
4) Вставить в HTML как есть: `<body> <svg ...> ... </svg> </body>`

4 способ хорош, можно стилизовать и мучать эту svg'шку как душе угодно.

Но минус в том, что если SVG занимает, к примеру, 5 килобайт, то ты всегда эти 5 килобайт будешь загружать, потому что это часть разметки. Но если тебе не нужна гибкость, а просто векторная картинка, которая всегда одна и та же, а логотип таковой и является, то лучше подключить через 1, 2 или 3 способ и тогда браузер единожды загрузит эту картинку, а потом будет брать из кэша.

2019-03-15 19:38 UTC, evgenymarkov commented on src/index.html
> +        <ul class="letters" id="hidden">
id тут для чего? Можешь использовать 2 класса.

Обычно id используют в ситуациях, когда на элемент будут как-то ссылаться, например, через `<label for="some-id">`, либо будут получать его в JS через `getElementById('#some-id')`, а в остальных случаях используют классы.

2019-03-15 19:38 UTC, evgenymarkov commented on src/index.html
> +        <div class="description"><label class="yandex">Яндекс</label> Почта</div>
Это логотипы. Подставляя их текстом ты не сможешь достичь того же стиля, который задумывал дизайнер. Лучше всего в таких случаях подставлять картинки в формате SVG.

2019-03-15 19:38 UTC, evgenymarkov commented on src/index.html
> +            <a href="#hide" id="close_article">
id кажется лишний

2019-03-15 19:38 UTC, evgenymarkov commented on src/index.html
> +                    <li class="copyright"> &copy; 2001-2019, Яндекс</li>
Не похоже на список. У тебя их слишком много и используются зачастую не к месту.

2019-03-15 19:38 UTC, evgenymarkov commented on src/index.html
> +                    <li class="copyright"> Реклама</li>
Класс противоречит содержимому, `copyright` у тебя на странице только один: `&copy 2001-2018, Яндекс`

2019-03-15 19:38 UTC, evgenymarkov commented on src/style.css
> +    font-family: YSText;
Можно записать в сокращенной форме:
font: [font-style||font-variant||font-weight] font-size [/line-height] font-family | inherit

2019-03-15 19:38 UTC, evgenymarkov commented on src/style.css
> +    font-family: HelveticaNeue;
Можно записать в сокращенной форме:
font: [font-style||font-variant||font-weight] font-size [/line-height] font-family | inherit

2019-03-15 19:38 UTC, evgenymarkov commented on src/style.css
> +
Одинаковые селекторы можно объединить:

```css
.deleted {
    margin-top: 8px;
}

.spam {
    margin-top: 8px;
}

.drafts {
    margin-top: 8px;
}

.folder {
    margin-top: 8px;
}
```

============>

```
.deleted,
.spam,
.drafts,
.folder {
    margin-top: 8px;
}
```

2019-03-15 19:38 UTC, evgenymarkov commented on src/style.css
> +    padding-top: 11.5px;
Дробные значения в пикселях лучше не использовать. Многие браузеры реагируют на них по разному и из-за этого могут проявиться визуальные отличия.

2019-03-15 19:38 UTC, evgenymarkov commented on src/index.html
> +            <div class="write_text">Написать</div>
В интерфейсе это выглядит как кнопка, значит кнопкой в разметке она и должна быть. Мало достигнуть соответствующего внешнего вида и поведения элемента, важно ещё сделать так чтобы твои намерения были поняты поисковым роботом, экранным диктором, а для того чтобы этого достичь нужно не забывать о семантике.

2019-03-15 19:38 UTC, evgenymarkov commented on src/index.html
> +        <li class="letter_text sent">Отправленные</li>
Эти элементы должны быть либо кнопками, либо ссылками

2019-03-15 19:38 UTC, evgenymarkov commented on src/index.html
> +    <div class="mail_box" id="show">
id опять же лишний

2019-03-15 19:38 UTC, evgenymarkov commented on src/index.html
> +                    <div class="ya_letter">Я</div>
Не совсем ya_letter это. Здесь логотип компании отправившей письмо. Соответственно название класса тоже должно быть другим.

И элемент не центрирован в круге.

2019-03-15 19:38 UTC, evgenymarkov commented on src/style.css
> +    border: solid 1px #e2e2e2;
Если убрать, то будет ближе к макету. А вообще этот элемент не нужен на странице. Border должен быть у footer'а.

2019-03-16 20:17 UTC, RuzikHan commented on src/index.html
> +    <div class="mail_box" id="show">
Этот id используется для открытия статьи, поэтому вроде не лишний.

2019-03-16 20:17 UTC, RuzikHan commented
Исправлено

2019-03-19 15:23 UTC, evgenymarkov approved these changes

2019-03-19 15:23 UTC, closed without merging