Галкин Егор, M3335, HW2
itmo2019/task2 pull request #2
Opened 2019-03-08 19:52 UTC by egalkin

2019-03-16 21:35 UTC, evgenymarkov requested changes

2019-03-16 21:35 UTC, evgenymarkov commented on src/index.html
> +                    <p class="IncomingMessages TextOverflow">
Остальные пункты меню отделены от "Входящие". Стоит поместить их в один список, а стили текущего пункта регулировать навешиванием дополнительного класса.

2019-03-16 21:35 UTC, evgenymarkov commented on src/index.html
> +                    <p class="IncomingMessages TextOverflow">
А ещё это должна быть либо кнопка, либо ссылка.

2019-03-16 21:35 UTC, evgenymarkov commented on src/index.html
> +                    Переслать
Action'ы должны быть button'ами, у нативных кнопок надо сбросить стили

2019-03-16 21:35 UTC, evgenymarkov commented on src/index.html
> +            <main class="ContentMain">
В документе не должно быть больше 1 тэга `main`.

2019-03-16 21:35 UTC, evgenymarkov commented on src/index.html
> +                        <div class="Oval"><p class="Ya">Я</p></div>
Таки это не Oval, а логотип фирмы/аватар человека. Для элемента можно дать более точное название класса.

2019-03-16 21:35 UTC, evgenymarkov commented on src/index.html
> +                <hr class="SeparateLine">
Разделитель выглядит жирно, можно обойтись вовсе без `<hr>` и делать линии с помощью свойства `border` у строк с письмами

2019-03-16 21:35 UTC, evgenymarkov commented on src/index.html
> +                    <li><a href="index.html"><p class="ListElem TextOverflow">Отправленные</p></a></li>
У меня появились троеточия, но ведь эти строки фиксированной ширины и вряд ли могут изменяться с течением времени, лучше сделать так чтобы пункты меню показывались полностью.
![image](https://user-images.githubusercontent.com/16443248/54481550-cbcbda80-4857-11e9-98f4-0d89276fe031.png)

2019-03-16 21:35 UTC, evgenymarkov commented on src/index.html
> +                    <li><a href="index.html"><p class="ListElem TextOverflow">Удаленны</p></a></li>
При открытии страницы на секунду показывается контент попапа. Вероятно сделано это неосознанно, предлагаю пофиксить поведение.

2019-03-16 21:35 UTC, evgenymarkov commented on src/index.html
> +                    Помощь и обратная связь      Реклама      &copy; 2001 &mdash; 2018, Яндекс
Это должны быть разные элементы, причём в строке 3 ссылки

2019-03-16 21:35 UTC, evgenymarkov commented on src/index.html
> +
В голом HTML, при отсутствии системы сборки, лишние пустые строки и пробелы могут привести к появлению визуальных искажений, неожиданных отступов. Убирать форматирование сейчас не призываю, просто имей в виду.

В React такой проблемы нет, как и в минифицированном HTML каким-нибудь вебпаком.

2019-03-16 21:35 UTC, evgenymarkov commented on src/styles.css
> +    margin-bottom: 4.8px;
Остерегайся дробных значений пикселей. Браузеры по разному интерпретируют их и могут появиться неожиданные артефакты.

2019-03-16 21:35 UTC, evgenymarkov commented on src/styles.css
> +    background-color: #000000;
Можно сократить до `#000`, как и `#ffffff` до `#fff`

2019-03-16 21:35 UTC, evgenymarkov commented on src/styles.css
> +.Header {
Классы не по [БЭМу](https://ru.bem.info/methodology/naming-convention/#правила-формирования-имен), но это давай в третьей домашке

2019-03-16 21:35 UTC, evgenymarkov commented on src/index.html
> +            <header class="Actions">
[Где и когда можно использовать тэг header](https://stackoverflow.com/a/23135341)

2019-03-16 21:35 UTC, evgenymarkov commented on src/styles.css
> +a {
Лучше писать селекторы для классов, а не тегов. Также рекомендую избегать использования `!important`.

2019-03-16 21:35 UTC, evgenymarkov commented on src/styles.css
> +    float: right;
Лишнее правило, ни на что этот `float` не влияет

2019-03-16 21:35 UTC, evgenymarkov commented on src/styles.css
> +    height: 90vh;
Аккуратнее с `vh`. Некоторыми браузерами эта единица измерения поддерживается из рук вон плохо.

2019-03-16 21:35 UTC, evgenymarkov commented on src/styles.css
> +    padding: 1.5% 2% 2% 0;
Здесь лучше подойдут фиксированные значения в пикселях. Ну и строки пустые не оставляй.

2019-03-16 21:35 UTC, evgenymarkov commented on src/styles.css
> +    font-family: HelveticaNeue;
Можно записать в одно сокращенное правило:
```css
font: [font-style||font-variant||font-weight] font-size [/line-height] font-family | inherit
```

2019-03-16 21:35 UTC, evgenymarkov commented on src/styles.css
> +    font-family: HelveticaNeue;
Можно записать в одно сокращенное правило:
```css
font: [font-style||font-variant||font-weight] font-size [/line-height] font-family | inherit
```

2019-03-16 21:35 UTC, evgenymarkov commented on src/styles.css
> +    font-style: normal;
Можно записать в одно сокращенное правило:
```css
font: [font-style||font-variant||font-weight] font-size [/line-height] font-family | inherit
```

2019-03-17 20:32 UTC, egalkin commented on src/styles.css
> +    margin-bottom: 4.8px;
Да, я как раз хотел уточнить, если в макете такое встречается, то это скорее всего просто случайность?

2019-03-17 20:35 UTC, egalkin commented on src/styles.css
> +    height: 90vh;
А, что тогда делать в случае, если я хочу чтоб высота изменялась в зависимости от размера vieport? Просто если ширину мы можем задавать в процентах и она нормально высчитывается, то высота высчитывается только при явном задании высоты родителя.

2019-03-19 15:16 UTC, evgenymarkov commented on src/styles.css
> +    margin-bottom: 4.8px;
Да, скорее случайность)

2019-03-19 15:18 UTC, evgenymarkov commented on src/styles.css
> +    height: 90vh;
Если нужно поддерживать IE, то придётся применить [тёмное колдунство](https://stackoverflow.com/questions/25177791/ie11-flexbox-and-vh-height-units-not-compatible), но заниматься им без необходимости не призываю) Просто нужно иметь в виду.

2019-03-19 15:20 UTC, evgenymarkov approved these changes

2019-03-19 15:20 UTC, closed without merging