Task2
itmo2019/task2 pull request #20
Opened 2019-03-09 17:12 UTC by airosso

Сделала с js

2019-03-13 08:24 UTC, mokhov commented
Многие проблемы видны невооруженным глазом
![Яндекс Почта 2019-03-13 11-22-16](https://user-images.githubusercontent.com/357689/54263737-95097200-4582-11e9-998c-62930c78159b.jpg)
![Яндекс Почта 2019-03-13 11-23-02](https://user-images.githubusercontent.com/357689/54263738-95097200-4582-11e9-88ed-a5cd1ed1c591.jpg)
![Яндекс Почта 2019-03-13 11-23-21](https://user-images.githubusercontent.com/357689/54263739-95097200-4582-11e9-8549-4a63a4a0e337.jpg)
![Яндекс Почта 2019-03-13 11-24-10](https://user-images.githubusercontent.com/357689/54263740-95097200-4582-11e9-9373-9f86593f9344.jpg)

2019-03-13 08:29 UTC, mokhov requested changes

2019-03-13 08:29 UTC, mokhov commented on src/mail.html
> +    <div class = "menu">
Разность стилистики написания то с пробелами, то без пробелов наводит на мысль, что часть кода была у кого-то скопирована

2019-03-13 08:29 UTC, mokhov commented on src/mail.html
> +        <button class="rectangle-write">
`button` в целом это хорошо, но сейчас интерфейс совсем никак не даёт понять о том, что по этому элементу можно кликать

2019-03-13 08:29 UTC, mokhov commented on src/mail.html
> +        <button class="rectangle-write">
Ну и все же ссылки лучше

2019-03-13 08:29 UTC, mokhov commented on src/mail.html
> +                <div class="kind">Переслать</div>
А тут, внезапно, это просто div'ы хотя это тоже ссылки

2019-03-13 08:29 UTC, mokhov commented on src/mail.html
> +                <div class="round">Я</div>
Здесь может как не быть ничего, так и быть картинка

2019-03-13 08:29 UTC, mokhov commented on src/mail.html
> +                <div class="who"><b>Яндекс.Паспорт</b></div>
b не очень релеватно использовать, жирность показывает что это письмо не прочитано, и у тебя даже есть на что завязаться

2019-03-13 08:29 UTC, mokhov commented on src/mail.html
> +                <div class="info">Реклама</div>
Это тоже ссылки

2019-03-13 08:29 UTC, mokhov commented on src/mail.html
> +        function showStory() {
Увы не могу принять, показ письма можно сделать без JS

2019-03-13 08:29 UTC, mokhov commented on src/style.css
> +    background-color: #ffffff;
`ffffff` -> `fff`

2019-03-13 08:55 UTC, airosso commented on src/mail.html
> +    <div class = "menu">
Не списывала

2019-03-14 18:51 UTC, airosso commented
Исправила все недочеты

2019-03-21 15:56 UTC, mokhov commented
В целом ок, но в инпуте текст серый даже когда я вводишь. Ну и сам инпут не похож

2019-03-21 15:56 UTC, mokhov commented
Крестик можно реализовать через `reset`

2019-03-21 15:58 UTC, mokhov approved these changes

2019-03-21 15:58 UTC, closed without merging