Implement task2
itmo2019/task2 pull request #21
Opened 2019-03-09 17:35 UTC by nikvoloshin

2019-03-14 07:56 UTC, underoot requested changes
В целом очень даже неплохо, только небольшие замечания

2019-03-14 07:56 UTC, underoot commented on index.html
> +            <a href="https://yandex.ru" id="logo-yandex" class="logo-text">Яндекс</a>
Логотип лучше делать картинкой

2019-03-14 07:56 UTC, underoot commented on index.html
> +                <img src="img/icons/hamburger-menu.png" width="16" height="16" id="logo-hamburger-icon" alt=""/>
Не стоит оставлять `alt` пустым. Хорошая практика доступности интерфейсов — предоставлять альтернативный текст к картинке

2019-03-14 07:56 UTC, underoot commented on index.html
> +                        <div class="my-checkbox"></div>
Чекбоксы нужно сделать чекбоксами

2019-03-14 07:56 UTC, underoot commented on css/style.css
> +#main-header {
А почему не использовать классы, так сказать для единообразия

2019-03-14 07:56 UTC, underoot commented on css/style.css
> +    /* Sorry, svg is too hard for me */
Brace yourself!

2019-03-15 01:33 UTC, nikvoloshin commented on index.html
> +            <a href="https://yandex.ru" id="logo-yandex" class="logo-text">Яндекс</a>
Сделал
Немного непохоже на оригинал, но я не нашел в сети этот логотип в хорошем качестве, а задизайнить получилось только такой

2019-03-15 01:34 UTC, nikvoloshin commented on index.html
> +                <img src="img/icons/hamburger-menu.png" width="16" height="16" id="logo-hamburger-icon" alt=""/>
Поправил

2019-03-15 01:35 UTC, nikvoloshin commented on index.html
> +                        <div class="my-checkbox"></div>
Сделал чекбоксы и добавил выделение действий над письмами и писем по чеку (кроме первого письма, не смог придумать как совместить выделение письма и открытие статьи)

2019-03-15 01:36 UTC, nikvoloshin commented on css/style.css
> +#main-header {
Не читал про БЭМ во время написания таски и думал, что логично давать id объекту в единственном экземпляре и class - повторяющимся
Исправил

2019-03-15 01:39 UTC, nikvoloshin commented
Также исправил залезание текста под крестик в строке поиска

2019-03-15 01:52 UTC, nikvoloshin commented
Ну  и добавил подсветку действий при наведении, если включен чекбокс. Просто, чтобы было..

2019-03-16 12:04 UTC, underoot approved these changes

2019-03-16 12:04 UTC, closed without merging