task2 done
itmo2019/task2 pull request #22
Opened 2019-03-09 17:38 UTC by RuslanKhalimov

2019-03-13 13:52 UTC, rmbaad requested changes
В целом неплохо, но надо доделать

2019-03-13 13:52 UTC, rmbaad commented on styles.css
> +    height: 600px;
Всё-таки задавать высоту для body не очень хорошо, задай для какого-нибудь контейнера внутри

2019-03-13 13:52 UTC, rmbaad commented on styles.css
> +    float: left;
Тут это ни к чему

2019-03-13 13:52 UTC, rmbaad commented on styles.css
> +    float: left;
Можно переделать на инлайн блоки

2019-03-13 13:52 UTC, rmbaad commented on styles.css
> +.header__yandex-mail-logo {
Логотип не очень похож на макет

2019-03-13 13:52 UTC, rmbaad commented on styles.css
> +.header__search-input {
Инпут совсем не похож на тот что в макете

2019-03-13 13:52 UTC, rmbaad commented on styles.css
> +    height: 88.7%;
Странная высота) и она кажется вообще не нужна тут

2019-03-13 13:52 UTC, rmbaad commented on styles.css
> +    position: relative;
Лишнее

2019-03-13 13:52 UTC, rmbaad commented on styles.css
> +    border-radius: 3px;
Ещё бы рамку убрать чтобы было как в макете. Посмотри, можно сделать border-radius так чтобы не было самой рамки (например transparent или цветом кнопки)

2019-03-13 13:52 UTC, rmbaad commented on styles.css
> +    height: 32px;
С выравниваем текста по высоте проблемки

2019-03-13 13:52 UTC, rmbaad commented on styles.css
> +    font-stretch: normal;
Откуда это и что это?

2019-03-13 13:52 UTC, rmbaad commented on index.html
> +            <div class="menu__menu-button">Входящие</div>
Лучше сделать списком

2019-03-13 13:52 UTC, rmbaad commented on index.html
> +            <div class="menu__menu-button">Отправленные</div>
Пункты меню должны быть ссылками

2019-03-13 13:52 UTC, rmbaad commented on index.html
> +            <div class="content__content-line-checkbox"></div>
Чекбоксы должны быть чекбоксами, а не просто квадратиками

2019-03-13 13:52 UTC, rmbaad commented on styles.css
> +.content__footer {
Позиционирование текста в футере совсем не как в макете

2019-03-13 13:52 UTC, rmbaad commented on index.html
> +            <img class="content__raccoon-image" src="images/raccoon.png" alt="raccoon">
Обтекания фигурной картинки кажется нет

2019-03-16 18:04 UTC, RuslanKhalimov commented
Обтекание картинки есть по кругу, а на firefox по контуру картинки

2019-03-18 08:53 UTC, rmbaad approved these changes
Футер не совсем такой, какой должен быть, но это мелочь. В остальном на мой взгляд ок

2019-03-18 08:53 UTC, closed without merging