Копица Антон, M3335
itmo2019/task2 pull request #24
Opened 2019-03-09 18:27 UTC by Amoniy

2019-03-15 08:04 UTC, mokhov commented
![Почта 2019-03-15 11-03-30](https://user-images.githubusercontent.com/357689/54416997-01ff4200-4712-11e9-9ed2-b719323b5512.jpg)
![почта - Untitled - Zeplin 2019-03-15 11-03-13](https://user-images.githubusercontent.com/357689/54417002-04619c00-4712-11e9-82a8-b96d5fcc123e.jpg)
По вертикали выравнивание немного другое

2019-03-15 08:06 UTC, mokhov commented
Так делать не стоит, т.к там могут быть тоже важные пункты
![Почта 2019-03-15 11-06-04](https://user-images.githubusercontent.com/357689/54417153-65896f80-4712-11e9-9529-c45c7aaf4be5.jpg)

2019-03-15 08:10 UTC, mokhov commented
Если много текста, то футер взаимодействует с картинкой, это не очень ок
![Почта 2019-03-15 11-10-11](https://user-images.githubusercontent.com/357689/54417360-fbbd9580-4712-11e9-921c-a412174e3b7b.jpg)

2019-03-15 08:10 UTC, mokhov requested changes

2019-03-15 08:10 UTC, mokhov commented on style.css
> +    opacity: 0.4;
Это создаёт ситуацию, когда всё поле наследует этот стиль. Но если посмотреть в макете, то у текста нет прозрачности

2019-03-15 08:10 UTC, mokhov commented on index.html
> +<html lang="en">
Почему `en`?

2019-03-15 08:10 UTC, mokhov commented on index.html
> +                         width="153px" height="31px">
px лишнее

2019-03-15 08:10 UTC, mokhov commented on index.html
> +                    <img class="message-image" src="resources/dog.png" alt="dog" align="right">
А тут вдруг нет размеров :(

2019-03-15 08:10 UTC, mokhov commented on style.css
> +    width: calc(100% - 44px);
Это можно сделать и без `calc`?

2019-03-15 08:10 UTC, mokhov commented on style.css
> +    font-size: 15px;
Можно это и следующее правило объединить

2019-03-15 08:10 UTC, mokhov commented on style.css
> +    background-color: #ff3333;
А почему тут не сократил?

2019-03-16 11:01 UTC, Amoniy commented
Поправил недочеты. Строка действий с письмом для сохранения всех пунктов теперь добавляет скролл как при переполнении количества элементов, так и при длинных текстах. 
Можно сделать и обрезание текста, но тогда, и правда, будет теряться важная информация. Правится это одной строчкой, так что оставил так, как кажется лучше. Ломаться ничего не будет. И кажется, что действия с сообщениями не будут очень длинными по описанию.

2019-03-23 03:24 UTC, closed without merging