task2
itmo2019/task2 pull request #26
Opened 2019-03-09 19:15 UTC by BirdyDeveloper

В качестве первого письма - первая домашка, к которой добавлена картинка с текстом в конец. Там использовался js, но так как первое задание не запрещало, а к этому оно не относится, я считаю, что это не нарушает требований на второе задание.

2019-03-15 13:02 UTC, trixartem requested changes
Есть расхождения с макетом, поправь, пожалуйста.

2019-03-15 13:02 UTC, trixartem commented on src/css/essay.css
> +body {overflow-x: hidden; background-color: white}
white -> #fff

2019-03-15 13:02 UTC, trixartem commented on src/css/essay.css
> +	width: calc(var(--n) * 100%);
--n  
Но зачем?
Пиши код проще, зачем его усложнять конструкциями?

2019-03-15 13:02 UTC, trixartem commented on src/css/essay.css
> +	/* overflow-y: hidden; */
Можно убрать

2019-03-15 13:02 UTC, trixartem commented on src/css/essay.css
> +	display: flex;
Флексы нельзя использовать

2019-03-15 13:02 UTC, trixartem commented on src/css/essay.css
> +	transform: translate(calc(var(--i, 0)/var(--n)*-100%));
Тут тоже не понятно, для чего такая формула

2019-03-15 13:02 UTC, trixartem commented on src/css/essay.css
> +	height: 40%;
Все равно не работает

2019-03-15 13:02 UTC, trixartem commented on src/css/essay.css
> +  display: flex;
Флексы нельзя

2019-03-15 13:02 UTC, trixartem commented on src/css/essay.css
> +#interface-table {
Почему иногда id, а иногда class? Давай придерживаться одному стилю. Рекомендую везде использовать классы, потому что в реальности нет гарантии, что id не повторится

2019-03-15 13:02 UTC, trixartem commented on src/css/essay.css
> +  background: url(http://effects1.ru/png/kartinka/1/koty/1/kitten_cat_4-320.png) no-repeat left top;
left -> 0
top -> 0

2019-03-15 13:02 UTC, trixartem commented on src/css/index.css
> +    0 7px 0 0 black,
black -> #000

2019-03-15 13:02 UTC, trixartem commented on src/css/index.css
> +  font-family: "Arial";
Нет фолбэка до системных шрифтов

2019-03-15 13:02 UTC, trixartem commented on src/css/index.css
> +  width: calc(200 / 589 * 100%);
Не понятно, что обозначают эти вычисления. Надо написать комменты или упростить

2019-03-15 13:02 UTC, trixartem commented on src/css/index.css
> +  font-family: "Arial";
А разве не на всей странице Arial?

2019-03-15 13:02 UTC, trixartem commented on src/css/index.css
> +/* #open-message1:not(:checked) ~ body {
Комменты можно убрать

2019-03-15 13:02 UTC, trixartem commented on src/essay.js
> +// https://css-tricks.com/simple-swipe-with-vanilla-javascript/
К сожаления js нельзя. Мы не просто так запрещаем его использовать в эти задачах. Что бы поломать голову, как можно сделать версткой.

2019-03-15 13:02 UTC, trixartem commented on src/index.html
> +      <nav style="display: inline">
А для чего инлайнить?

2019-03-16 17:05 UTC, BirdyDeveloper commented on src/css/essay.css
> +body {overflow-x: hidden; background-color: white}
Заменил

2019-03-16 17:05 UTC, BirdyDeveloper commented on src/css/essay.css
> +	width: calc(var(--n) * 100%);
Это было нужно для возможности простого добавления нового элемента в "альбом". Убрал.

2019-03-16 17:05 UTC, BirdyDeveloper commented on src/css/essay.css
> +	/* overflow-y: hidden; */
Убрал

2019-03-16 17:05 UTC, BirdyDeveloper commented on src/css/essay.css
> +	display: flex;
Осталось с предыдущего домашнего задания, прошу прощения. Убрал использование

2019-03-16 17:05 UTC, BirdyDeveloper commented on src/css/essay.css
> +	transform: translate(calc(var(--i, 0)/var(--n)*-100%));
Для перелистывания альбома. Осталось от первого домашнего задания. Убрал

2019-03-16 17:05 UTC, BirdyDeveloper commented on src/css/essay.css
> +	height: 40%;
Что бы тут не работало - убрал

2019-03-16 17:05 UTC, BirdyDeveloper commented on src/css/essay.css
> +  display: flex;
Осталось с предыдущего домашнего задания, прошу прощения. Убрал использование

2019-03-16 17:05 UTC, BirdyDeveloper commented on src/css/essay.css
> +#interface-table {
Осталось с предыдущего домашнего задания, которое было как раз на то, чтобы попрактиковаться с этим, насколько я понимаю, в том числе. Последовал рекомендации, спасибо

2019-03-16 17:05 UTC, BirdyDeveloper commented on src/css/essay.css
> +  background: url(http://effects1.ru/png/kartinka/1/koty/1/kitten_cat_4-320.png) no-repeat left top;
Добавил, правда не очень понимаю зачем. Можете подсказать, пожалуйста?

2019-03-16 17:05 UTC, BirdyDeveloper commented on src/css/index.css
> +    0 7px 0 0 black,
Заменил, но не понимаю, зачем. Я правильно понимаю, что даже lightskyblue нужно заменять на hex представление этого цвета?

2019-03-16 17:06 UTC, BirdyDeveloper commented on src/css/index.css
> +  font-family: "Arial";
Добавил до serif

2019-03-16 17:06 UTC, BirdyDeveloper commented on src/css/index.css
> +  width: calc(200 / 589 * 100%);
Добавил и поправил

2019-03-16 17:06 UTC, BirdyDeveloper commented on src/css/index.css
> +  font-family: "Arial";
Действительно

2019-03-16 17:06 UTC, BirdyDeveloper commented on src/css/index.css
> +/* #open-message1:not(:checked) ~ body {
Убрал.

2019-03-16 17:06 UTC, BirdyDeveloper commented on src/essay.js
> +// https://css-tricks.com/simple-swipe-with-vanilla-javascript/
Остался с предыдущего домашнего задания - убрал.

2019-03-16 17:06 UTC, BirdyDeveloper commented on src/index.html
> +      <nav style="display: inline">
чтобы в строчку было

2019-03-20 05:46 UTC, trixartem commented on src/index.html
> +      <nav style="display: inline">
Можно же добавить класс и в CSS задать свойства

2019-03-20 06:03 UTC, trixartem requested changes
Есть несколько замечаний поверстке:
- Если много писем, то они вылазят за пределы родителя, а должны растягивать его
- Нет эффектов при наведении на пункты меню слева
- Везде шрифт лучше сделать одинаковый - без засечек
- Поиск не очень похож на тот, что в макете

+ за то что добавить ellipsis

2019-03-20 06:03 UTC, trixartem commented on src/css/essay.css
> +body {background-color: #fff}
Задай всему сайту шрифт Arial, так будет больше походить на макет)

2019-03-20 06:03 UTC, trixartem commented on src/css/essay.css
> +  font-family: "Times New Roman", Times, serif;
Если есть глобальный шрифт, то можно убрать этот

2019-03-20 06:03 UTC, trixartem commented on src/css/essay.css
> +body {background-color: #fff}
А вижу, что ниже еще есть body, тогда лучше объединить

2019-03-20 06:03 UTC, trixartem commented on src/css/index.css
> +#open-message1 {
все display: none, можно объединить в один селектор

2019-03-20 06:03 UTC, trixartem commented on src/essay.html
> +  <header style="width: 100%">
Лучше все инлайн-стили унести в CSS, так правильнее - разделять ответственность

2019-03-20 06:03 UTC, trixartem commented on src/index.html
> +          <time datetime="2019-08-06" class="message-time">6 авг</time>
👍

2019-03-20 06:03 UTC, trixartem commented on src/index.html
> +      <input id="select-all" type="checkbox" style="width: 16px; height: 16px">
Тут тоже инлайн стили

2019-03-22 12:55 UTC, BirdyDeveloper commented on src/css/index.css
> +#open-message1 {
Не очень понял

2019-03-22 12:55 UTC, BirdyDeveloper commented on src/css/essay.css
> +  font-family: "Times New Roman", Times, serif;
Убрал

2019-03-22 12:55 UTC, BirdyDeveloper commented on src/essay.html
> +  <header style="width: 100%">
Сделал, но для котика не сделал, потому что это какая-то жесть каждому котик-диву делать свой класс.

2019-03-22 12:55 UTC, BirdyDeveloper commented
> Если много писем, то они вылазят за пределы родителя, а должны растягивать его
Думал, что в этом задании не нужно (было в третьем) - теперь есть тут 
> Нет эффектов при наведении на пункты меню слева
Теперь есть
> Поиск не очень похож на тот, что в макете
Убрать растяжение его?

2019-03-25 17:15 UTC, trixartem commented
Задание принятно.

2019-03-25 17:15 UTC, closed without merging