Гламозда Виталий М3335
itmo2019/task2 pull request #28
Opened 2019-03-09 19:24 UTC by Sketcher14

2019-03-15 13:33 UTC, evgenymarkov requested changes
В конечном счёте все извращения с процентами свелись к сайту, который отображается в окошке 800x600. Нужно сделать так, чтобы сайт хорошо выглядел на любом десктопе.

2019-03-15 13:33 UTC, evgenymarkov commented on hw2/index.html
> +    <header id="mainHeader">
Именовать классы рекомендуется в соответствии с какой-либо методологией. Наиболее популярной является БЭМ. Рекомендую в следующих домашних заданиях ориентироваться на неё. Почитать можно [тут](https://ru.bem.info/methodology/css/#Именование).

2019-03-15 13:33 UTC, evgenymarkov commented on hw2/index.html
> +        <div id="menu">
Обычно id используют в ситуациях, когда на элемент будут как-то ссылаться, например, через `<label for="some-id">`, либо будут получать его в JS через `getElementById('#some-id')`, а в остальных случаях используют классы. 

Поменяй id на класс и обращайся к нему из CSS.

2019-03-15 13:33 UTC, evgenymarkov commented on hw2/index.html
> +            <div></div>
Лучше использовать SVG иконки, чем пытаться с помощью CSS повторить те или иные фигуры.

Подробнее о способах подключения svg можно почитать здесь
https://css-tricks.com/using-svg/

Вкратце опишу тут

Способы подключения SVG:

1) В CSS указать `url('url картинки или путь до файла')`
2) Подключить через `<img src="..." />`
3) Подключить через object: `<object type="image/svg+xml" data="url или путь до файла"> </object>`
4) Вставить в HTML как есть: `<body> <svg ...> ... </svg> </body>`

4 способ хорош, можно стилизовать и мучать эту svg'шку как душе угодно.

Но минус в том, что если SVG занимает, к примеру, 5 килобайт, то ты всегда эти 5 килобайт будешь загружать, потому что это часть разметки. Но если тебе не нужна гибкость, а просто векторная картинка, которая всегда одна и та же, а логотип таковой и является, то лучше подключить через 1, 2 или 3 способ и тогда браузер единожды загрузит эту картинку, а потом будет брать из кэша.

2019-03-15 13:33 UTC, evgenymarkov commented on hw2/index.html
> +            <span id="yandex">Яндекс</span> <span id="mail">Почта</span>
Это логотипы. Подставляя их текстом ты не сможешь достичь того же стиля, который задумывал дизайнер. Лучше всего в таких случаях подставлять картинки в формате SVG.

2019-03-15 13:33 UTC, evgenymarkov commented on hw2/index.html
> +            <span id="cross">&times</span>
Любую HTML entity нужно закрывать с помощью `;`, например `&times;`

2019-03-15 13:33 UTC, evgenymarkov commented on hw2/index.html
> +
Не нужно оставлять пустые строки

2019-03-15 13:33 UTC, evgenymarkov commented on hw2/index.html
> +                <button>&copy 2001 - 2018, Яндекс</button>
Закрывай HTML entities

2019-03-15 13:33 UTC, evgenymarkov commented on hw2/index.html
> +                <button>&copy 2001 - 2018, Яндекс</button>
Это не `button`, а скорее `a`, как и "Помощь и обратная связь", как и "Реклама"

2019-03-15 13:33 UTC, evgenymarkov commented on hw2/styles/header.css
> +    src: url("../fonts/YandexSansText-Medium.ttf") format("truetype");
Есть более оптимизированные форматы шрифтов. На данный момент это `woff2`. Как минимум, он загружается быстрее. Подробные рекомендации можно почитать [тут](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization?hl=ru).

2019-03-15 13:33 UTC, evgenymarkov commented on hw2/styles/header.css
> +    margin-top: 20%;
Рекомендую использовать единицы измерения в таком приоритете:

px > rem > em/% > всё остальное

Абсолютные значения более просты в понимании и отладке, комбинировать em и px в реальных проектах приходится практически никогда

2019-03-15 13:33 UTC, evgenymarkov commented on hw2/styles/header.css
> +    color: #cccccc;
Цвета лучше записывать в hex представлении, в нижнем регистре и по возможности в сокращённой форме:

```
#fff
#f5f5dc
```

2019-03-15 13:33 UTC, evgenymarkov commented on hw2/styles/letter.css
> +/*div {
Мёртвый код, не оставляй такое

2019-03-15 13:33 UTC, evgenymarkov commented on hw2/styles/body.css
> +    font-family: "Segoe UI", serif;
Почему именно Segoe UI? Если он встроен в Windows, это не значит, что он есть в других ОС. Установи для всех одинаковый кастомный шрифт, либо сделай хорошо всем выставив цепочку системных шрифтов.

https://css-tricks.com/snippets/css/system-font-stack/

2019-03-15 13:33 UTC, evgenymarkov commented on hw2/styles/body.css
> +    /*border: 1px solid black;*/
Мёртвый код, удаляй

2019-03-16 11:54 UTC, Sketcher14 commented on hw2/styles/header.css
> +    color: #cccccc;
При сдаче первой дз Олег советовал записывать цвета через rgb, т.к отображение именованных цветов одинаково не гарантированно. В первом коммите я забыл об этом, потому что дедлайн был совсем скоро. Сейчас, я везде поменял на rgb, потому что для rgb запись, более привычна чем hex

2019-03-16 12:16 UTC, Sketcher14 commented
Немного переверстал, масштабирование по ширине работает, и как по мне, даже выглядит неплохо. А аналогичное масштабирование по высоте не работает, я не знаю почему. В следующих дз постараюсь это исправить. 
Переименовал классы по БЭМу, надеюсь правильно.

2019-03-16 12:19 UTC, Sketcher14 commented on hw2/styles/header.css
> +    margin-top: 20%;
А почему px самые приоритетные? Пиксели же задают фиксированное значение, и если менять размеры окна браузера, то блоки с фиксированной шириной и высотой начнут прыгать куда попало

2019-03-19 09:51 UTC, evgenymarkov approved these changes
Типографика очень сильно отличается от макета, отступы в шапке около логотипа и в поиске тоже.
Кнопки "Переслать", "Удалить", "Это спам!", "Прочитано" не реагируют на :hover, :active.

Давай пофиксим это всё в третьей лабе. И ссылки на 4500 строк тоже.

2019-03-19 09:51 UTC, evgenymarkov commented on hw2/images/yandex_logo.svg
> +       xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB4AAAAQ4CAYAAADo08FDAAAABHNCSVQICAgIfAhkiAAAIABJREFU
Охренеть, вот это извращение! PNG логотип закодированный в base64 сложен в SVG. Давай так не делать)

2019-03-19 09:52 UTC, closed without merging