Устинов Александр M3335
itmo2019/task2 pull request #29
Opened 2019-03-09 19:32 UTC by alexust27

add task2

2019-03-14 09:21 UTC, underoot requested changes
* Есть множество несоответствий макету. Стоит поправить (например размеры кнопок слева, размер инпута, положение крестика и т.п.)
* Плюс к этому комментария по ревью

2019-03-14 09:21 UTC, underoot commented on css/style.css
> +    /*height: 32px;*/
Размер инпута сейчас явно не соответствует макету

2019-03-14 09:21 UTC, underoot commented on css/style.css
> +.search > form > input[type="text"] {
Вместо длинной цепочки в селекторе можно просто навесить класс на нужный элемент. Такие стиле проще поддерживать, отвязываясь от структуры документа. Это относится и к другим подобным селекторам

2019-03-14 09:21 UTC, underoot commented on css/style.css
> +.mail-from {
При небольшом разрешении текст переносится на несколько строк и выглядит плохо

2019-03-14 09:21 UTC, underoot commented on css/style.css
> +.mail-from {
![image](https://user-images.githubusercontent.com/2480721/54343987-162f3a80-4651-11e9-8e9b-97bee6655bbf.png)
Примерно так

2019-03-14 09:21 UTC, underoot commented on index.html
> +                <div class="letter clearfix">
При клике на первый чекбокс, он не меняет свое положение. Вместо этого открывается письмо

2019-03-14 09:21 UTC, underoot commented on index.html
> +                    <data class="date" value="06.08">6 авг</data>
В случае с датами рекомендуется использовать `time`-элемент

2019-03-14 09:21 UTC, underoot commented on index.html
> +                    <b class="topic">Доступ к аккаунту востановлен</b>
Стилизацию стоит сделать средствами CSS

2019-03-14 09:21 UTC, underoot commented on css/style.css
> +.topic {
При большом количестве текста он переносится

2019-03-14 09:21 UTC, underoot commented on css/style.css
> +#my-topic {
А почему не класс?

2019-03-14 09:21 UTC, underoot commented on css/style.css
> +    height: calc(100vh - 14px);
С учетом, что `main-block` расположен явно не на самом верху страницы мы получаем, что содержимое этого блока при любом раскладе выходит за границу _viewport_

2019-03-14 09:21 UTC, underoot commented on index.html
> +                    <input type="checkbox" class="check check-percent">
А зачем класс `check-percent`?

2019-03-16 16:44 UTC, alexust27 commented on css/style.css
> +    /*height: 32px;*/
Почему не соответствует? В макете ширина макета 800px, а ширина поиска 301px, в итоге ширина 301/800 ~ 37%

2019-03-19 12:02 UTC, underoot commented
![image](https://user-images.githubusercontent.com/2480721/54604498-ec628300-4a57-11e9-98dd-568b30907b74.png)
Появилась такой вот верхний бордер над инпутом

2019-03-19 12:02 UTC, underoot commented on css/style.css
> +.bar-a {
Стоит выбрать название посемантичнее

2019-03-19 12:03 UTC, underoot commented
![image](https://user-images.githubusercontent.com/2480721/54604574-1fa51200-4a58-11e9-935a-0dbb4793d215.png)
Футер узковат

2019-03-19 12:04 UTC, underoot commented
![image](https://user-images.githubusercontent.com/2480721/54604598-2fbcf180-4a58-11e9-9480-85d364d8b3a4.png)
Расстояние между ссылками явно немакетные

2019-03-19 12:06 UTC, underoot commented on css/style.css
> +    /*height: 32px;*/
Тут речь про высоту, но ее, я видел, ты поправил

2019-03-19 20:51 UTC, alexust27 commented on css/style.css
> +.bar-a {
Я в 3 таске переименовал нормально)

2019-03-25 14:19 UTC, underoot commented
Со стилями немного беда осталась конечно. Есть проблема с футером и и кнопками над списком писем

2019-03-25 14:19 UTC, closed without merging