HW2: Балашов Ярослав, М3335
itmo2019/task2 pull request #3
Opened 2019-03-08 21:20 UTC by BreakChir

2019-03-10 18:27 UTC, mokhov commented
Привет. В описании задания есть ремарка про разные размеры, оно предполагает что интерфейс растягивается в зависимости от экрана браузера
![Яндекс Почта 2019-03-10 21-26-04](https://user-images.githubusercontent.com/357689/54089567-505fba00-437b-11e9-83fc-fc1fb7570733.jpg)

2019-03-10 18:29 UTC, mokhov commented
![Яндекс Почта 2019-03-10 21-28-29](https://user-images.githubusercontent.com/357689/54089596-961c8280-437b-11e9-8c0e-7046617cb459.jpg)
Ещё замечания по реализации

2019-03-10 18:43 UTC, mokhov requested changes
Есть что доработать

2019-03-10 18:43 UTC, mokhov commented on index.html
> +        <div class="menu-logo__line"></div>
Этот элемент не относится к логотипу, это скорее просто меню

2019-03-10 18:43 UTC, mokhov commented on index.html
> +        <div class="logo__elem logo__elem_yandex">Яндекс</div>
Чаще всего мы делаем это ссылкой на yandex.ru

2019-03-10 18:43 UTC, mokhov commented on index.html
> +        <div class="logo__elem logo__elem_mail">Почта</div>
Эту часть на корень сервиса, т.е mail.yandex.ru

2019-03-10 18:43 UTC, mokhov commented on index.html
> +    <div class="search inline-top">
Это инпут для ввода текста

2019-03-10 18:43 UTC, mokhov commented on index.html
> +                <div class="letter-box__checkbox inline-top"></div>
Имя элемента намекает на то что это должен быть `input type="checkbox"`

2019-03-10 18:43 UTC, mokhov commented on index.html
> +                <div class="letter-box__line-date inline-center">6 июля</div>
Напрочь забыто первое задание

2019-03-10 18:43 UTC, mokhov commented on index.html
> +                <div class="letter-box__line-photo inline-center">Я</div>
Кажется если всем элементам кроме первого нужен один и тот же класс, то что-то можно соптимизировать

2019-03-10 18:43 UTC, mokhov commented on index.html
> +            <div class="letter-box__info inline-center">Помощь и обратная связь</div>
Это явно ведь не текст, а ссылки

2019-03-10 18:43 UTC, mokhov commented on style.css
> +    font-family: YandexSansBold;
Это хорошее подключение, но, увы, не работает везде, рекомендую почитать вот эту статью https://css-tricks.com/snippets/css/using-font-face/

2019-03-10 18:43 UTC, mokhov commented on style.css
> +    transform: scale(0.725, 1.2);
Хорошая попытка ;-), но лучше тут использовать svg или картинку

2019-03-10 18:43 UTC, mokhov commented on style.css
> +    font-size: 15px;
Можно объединить в одном правиле `font`

2019-03-10 18:43 UTC, mokhov commented on style.css
> +    opacity: 0.5;
`.5`

2019-03-10 18:43 UTC, mokhov commented on style.css
> +.search {
![Яндекс Почта 2019-03-10 21-36-16](https://user-images.githubusercontent.com/357689/54089688-aaad4a80-437c-11e9-83cc-26b1df8cbbda.jpg)
при большом количестве текста поиску плохо

2019-03-10 18:43 UTC, mokhov commented on style.css
> +.letter-box__line {
Тут тоже не очень ок если много текста
![Яндекс Почта 2019-03-10 21-38-14](https://user-images.githubusercontent.com/357689/54089710-ea743200-437c-11e9-8999-6f9be7bba56c.jpg)

2019-03-10 18:43 UTC, mokhov commented on style.css
> +    color: #cccccc;
`cccccc` -> `ccc`

2019-03-10 18:43 UTC, mokhov commented on style.css
> +.letter-box__line-photo {
Это интересно что никто не спросил что это за элемент, но вообще это элемент предполагающий логотип сервиса, отправившего письмо, соответственно его может и не быть. Если его нет, то всё ломается :(
![Яндекс Почта 2019-03-10 21-43-12](https://user-images.githubusercontent.com/357689/54089761-8736cf80-437d-11e9-8175-694c4c408b3c.jpg)

2019-03-15 13:41 UTC, BreakChir commented
> ![Яндекс Почта 2019-03-10 21-28-29](https://user-images.githubusercontent.com/357689/54089596-961c8280-437b-11e9-8c0e-7046617cb459.jpg)
> Ещё замечания по реализации

В макете размеры этих текстов 11px и 13px

2019-03-16 15:34 UTC, BreakChir commented
Все сделал, проверьте пожалуйста

2019-03-21 14:54 UTC, mokhov commented
👍

2019-03-21 14:54 UTC, closed without merging