Pakulev Alexandr M3335
itmo2019/task2 pull request #30
Opened 2019-03-09 19:56 UTC by sashasashasasha151

2019-03-15 13:14 UTC, mokhov commented
1. Все шрифты и размеры больше чем в макете
2. Если макет сжать, то будет вот так
![Screenshot_2019-03-15 Yandex mail](https://user-images.githubusercontent.com/357689/54433595-5370f680-473d-11e9-945d-17c9d178f6ac.png)
3. При открытии письма текст наползает + работает клик в любом месте
![Yandex mail 2019-03-15 16-14-20](https://user-images.githubusercontent.com/357689/54433650-756a7900-473d-11e9-8878-480280df2ded.jpg)

2019-03-16 20:52 UTC, sashasashasasha151 commented
fix all

2019-03-23 03:39 UTC, mokhov commented
![Image 2019-03-23 06-39-08](https://user-images.githubusercontent.com/357689/54861190-66378c80-4d36-11e9-8e44-baa02b349883.jpg)

2019-03-23 03:40 UTC, mokhov commented
В Яндекс браузере всё ещё проблемы с выравниванием
![Yandex mail 2019-03-23 06-39-51](https://user-images.githubusercontent.com/357689/54861201-86674b80-4d36-11e9-8f6e-994e9bee3904.jpg)

2019-03-23 03:42 UTC, mokhov commented
У правой границы не хватает отступа
![Yandex mail 2019-03-23 06-41-47](https://user-images.githubusercontent.com/357689/54861222-c4fd0600-4d36-11e9-8959-87f68e2f81b6.jpg)

2019-03-23 03:45 UTC, mokhov commented
Из типичных ошибок не исправлена:
> Многие не поняли что означает буковка Я и синий кружок. Буковка Я – это логотип сервиса, в данном случае Яндекса, его может не быть или он может быть совершенно другой.

2019-03-23 03:45 UTC, mokhov requested changes
Есть что исправить

2019-03-23 03:45 UTC, mokhov commented on index.html
> +        <li id="new">Написать</li>
Для каких целей здесь нужен `id`?

2019-03-23 05:57 UTC, sashasashasasha151 commented
> В Яндекс браузере всё ещё проблемы с выравниванием
> ![Yandex mail 2019-03-23 06-39-51](https://user-images.githubusercontent.com/357689/54861201-86674b80-4d36-11e9-8f6e-994e9bee3904.jpg)

Мне нужно поставить все браузеры, чтобы понять что во всех всё работает?

2019-03-23 05:59 UTC, sashasashasasha151 commented
> Из типичных ошибок не исправлена:
> 
> > Многие не поняли что означает буковка Я и синий кружок. Буковка Я – это логотип сервиса, в данном случае Яндекса, его может не быть или он может быть совершенно другой.

У меня там объект с фоном в виде логотипа, разве так нельзя? Если не будет лого, не будет фона, если будет другой логотип, будет другой фон

2019-03-23 06:00 UTC, sashasashasasha151 commented
> Есть что исправить

А можно в виде исправленной версии отправлять 3е дз? Просто в нем это уже исправлено

2019-03-25 17:09 UTC, mokhov commented
> Мне нужно поставить все браузеры, чтобы понять что во всех всё работает? Или как можно это протестировать в хроме?

Не все, но основные

2019-03-29 15:59 UTC, sashasashasasha151 commented
Я не могу протестировать в Яндекс браузере, потому что не могу его установить на свой дистрибудив, также я так и не понял, что нужно сделать с логотипом и почему мой вариант плох

2019-04-06 07:23 UTC, closed without merging