Дроздов Глеб М3335
itmo2019/task2 pull request #31
Opened 2019-03-09 19:58 UTC by DrozdikGleb

2019-03-13 22:36 UTC, rmbaad requested changes

2019-03-13 22:36 UTC, rmbaad commented on index.html
> +<!DOCTYPE html>
Сделай пожалуйста чтобы это было больше похоже на то, что в макете.
Шрифты почти везде не те. В большей части я так понимаю просто не указан шрифт. Его можно указать для body например.
Логотип не похож на тот что в макете. Можно сделать картинкой или правильно подобрать шрифт.
Отступы в меню над письмами и в нижней части не те. Должно быть ровно и аккуратно.
Инпут с поиском не такой как в макете. Должна быть другая рамка как минимум.
Бордеры у писем не того цвета.

2019-03-16 16:40 UTC, DrozdikGleb commented on index.html
> +<!DOCTYPE html>
@rmbaad , поправил ваши замечания, не могли бы вы ещё раз посмотреть?

2019-03-18 09:04 UTC, rmbaad requested changes

2019-03-18 09:04 UTC, rmbaad commented on styles.css
> +li a {
Не стоит задавать стили для тегов, особенно для всех ссылок в списках. Например если придёт письмо с ссылками в списке, это затронет и их

2019-03-18 09:04 UTC, rmbaad commented on styles.css
> +    width: 20%;
Меню тянуть не надо, лучше сделать его фиксированным, иначе выглядит странно

2019-03-18 09:04 UTC, rmbaad commented on styles.css
> +    position: absolute;
Из-за position absolute при увеличении кол-ва писем, футер на них налезет. Лучше обернуть список писем в отдельный блок, дать ему min-height, а футер добавить после него. Тогда задание будет соответствовать требованиям

2019-03-19 15:37 UTC, DrozdikGleb commented on styles.css
> +    position: absolute;
@rmbaad , исправил все замечания. 
Что касается обёртки писем в отдельный блок с min-height, то она у меня была, поэтому просто убрал position absolute для footer.

2019-03-25 16:49 UTC, closed without merging