Козлов Кирилл M3339
itmo2019/task2 pull request #32
Opened 2019-03-09 20:05 UTC by kirill146

2019-03-15 19:14 UTC, mokhov commented
В целом очень неплохо, но есть что исправить. Например, при сжимании окна всё начинает наползать друг на друга
![Яндекс Почта 2019-03-15 22-13-51](https://user-images.githubusercontent.com/357689/54456549-b11e3680-476f-11e9-8c86-068f3222a82c.jpg)

2019-03-15 19:14 UTC, mokhov requested changes

2019-03-15 19:14 UTC, mokhov commented on essay-styles.css
> +    margin-left: 20px;
Немного отступы едут

2019-03-15 19:14 UTC, mokhov commented on essay-styles.css
> +	font-size: 20px;
Можно объединить с предыдущим правилом

2019-03-15 19:14 UTC, mokhov commented on styles.css
> +    overflow: hidden;
В этом задании это ок, но в целом так не стоит делать, т.к велик риск что внутри блока будет выпадушка

2019-03-15 19:14 UTC, mokhov commented on styles.css
> +#burger-menu-button:hover {
Не совсем понятно почему тут id

2019-03-15 19:14 UTC, mokhov commented on styles.css
> +.burger-menu-button-item {
А тут класс

2019-03-15 19:14 UTC, mokhov commented on styles.css
> +    width: calc(100% - 310px);
Лучше избегать calc, особенно в таком случае, когда можно воспользоваться просто рассчётами

2019-03-15 19:14 UTC, mokhov commented on styles.css
> +    color: #cccccc;
ccc

2019-03-16 20:40 UTC, kirill146 commented on styles.css
> +    width: calc(100% - 310px);
Подскажите пожалуйста, как избежать calc в данном случае? На float-ах вроде не получится написать так, чтобы не выталкивало дату

2019-03-23 03:46 UTC, closed without merging

2019-03-23 03:47 UTC, mokhov commented on styles.css
> +    width: calc(100% - 310px);
Вариантов всегда несколько.
Конкретно в данном случае у даты зарезервировано и фиксированно место, т.е ширина. Можно просто использовать margin