Бондарчук Юрий М3335
itmo2019/task2 pull request #33
Opened 2019-03-09 20:38 UTC by YuryBandarchuk16

2019-03-13 22:42 UTC, rmbaad requested changes
Работа очень сильно отличается от макета. Поправь пожалуйста.
Логотип совсем не такой как в макете.
В инпуте не те отступы и размеры, плюс он не является инпутом, туда нельзя ничего вписать.
Кнопка должна быть кнопкой, а не section.
Шрифты в письмах не те что в макете. Отступы в письмах так же не те.
При уменьшении экрана по высоте футер наезжает на письма.

2019-03-14 09:34 UTC, YuryBandarchuk16 commented
@rmbaad Не могли бы ли вы, пожалуйста, заново посмотреть на код?

Спасибо!

2019-03-14 20:18 UTC, rmbaad requested changes

2019-03-14 20:18 UTC, rmbaad commented on index.css
> +    height: calc(100vh - 50px);
👍

2019-03-14 20:18 UTC, rmbaad commented on index.css
> +  position: absolute;
Наверное забыл убрать. Вообще было бы хорошо и в хедере убрать абсолюты. Спозиционировать гамбургер, поиск и лого можно без них.

2019-03-14 20:18 UTC, rmbaad commented on index.css
> +  white-space: normal;
* — плохо. Подобные селекторы нагружают браузер и замедляют отрисовку. Лучше указать класс

2019-03-14 20:18 UTC, rmbaad commented on index.css
> +  display: table;
Это хак. По высоте можно ровнять через line-height, не критично

2019-03-14 20:18 UTC, rmbaad commented on index.css
> +.mail-navigation > * {
Оно и без `> *` должно сработать для всех потомков

2019-03-14 20:18 UTC, rmbaad commented on index.css
> +  display: table-cell;
И тут можно через line-height

2019-03-14 20:18 UTC, rmbaad commented on index.css
> +  box-shadow: inset 0 0 0 1px rgba(0, 0, 0, 0.2);
Кажется немного намудрил. Бордером было бы ближе к макету

2019-03-14 20:18 UTC, rmbaad commented on index.css
> +  opacity: 0.5;
Текст будет не очень хорошо видно при прозрачности. Возможно так выдаёт zeplin, ноу лучше просто подобрать цвета и сделать без прозрачности

2019-03-14 20:18 UTC, rmbaad commented on index.html
> +                Помощь и обратная связь
Должны быть ссылки

2019-03-14 20:19 UTC, rmbaad requested changes

2019-03-14 20:19 UTC, rmbaad commented on index.css
> +#search-bar-container {
id там где они не нужны. лучше классами

2019-03-14 20:19 UTC, rmbaad commented on index.css
> +  padding: 1px;
отступ не как в макете

2019-03-14 21:06 UTC, YuryBandarchuk16 commented on index.css
> +  box-shadow: inset 0 0 0 1px rgba(0, 0, 0, 0.2);
Это zeplin подсказал так сделать

2019-03-14 21:17 UTC, YuryBandarchuk16 commented on index.css
> +  display: table;
Значит можно оставить? :)

2019-03-15 18:28 UTC, YuryBandarchuk16 commented
@rmbaad Всё пофиксил

2019-03-16 14:50 UTC, rmbaad commented on index.css
> +.mail-footer a {
Лучше и здесь ссылкам дать свой класс, мало ли какие ещё ссылки могут появиться в этом блоке, и им возможно понадобится другой внешний вид

2019-03-16 14:52 UTC, rmbaad approved these changes
В целом неплохо

2019-03-16 14:52 UTC, rmbaad commented on index.html
> +            <img src="hamburger.svg" width="25px" height="25px">
Лучше дать класс и унести размеры в стили

2019-03-16 17:39 UTC, closed without merging