Яковлев Илья M3339
itmo2019/task2 pull request #34
Opened 2019-03-09 20:46 UTC by okayvlev

2019-03-14 09:37 UTC, underoot requested changes
* Размер шрифта не соответствует макету
* Замечания по ревью

2019-03-14 09:37 UTC, underoot commented on index.html
> +            <div class="logo header-element">
Логотип стоит сделать картинкой

2019-03-14 09:37 UTC, underoot commented on index.html
> +                <div class="footer">
Ссылки нужно сделать ссылками

2019-03-14 09:37 UTC, underoot commented on styles.css
> +    font-family: 'Yandex Sans';
А как насчет _fallback_-а без засечек?

2019-03-14 09:37 UTC, underoot commented on styles.css
> +#mailbox {
Для единообразия стили лучше сделать классом

2019-03-14 09:37 UTC, underoot commented on styles.css
> +#mailbox .mail .mail-element {
Длинных селекторов следует избегать, поскольку их сложно поддерживать

2019-03-14 09:37 UTC, underoot commented on index.html
> +                <div class="button primary">
Но это же кнопка

2019-03-14 09:37 UTC, underoot commented on index.html
> +                    <div class="header-element">
Это же тоже кнопки

2019-03-14 09:37 UTC, underoot commented on index.html
> +                            <div class="mail-element date">
Неплохо бы сделать элементом `time`

2019-03-14 09:37 UTC, underoot commented on index.html
> +                <div class="mail-contents">
Содержимое перекрывается футером

![image](https://user-images.githubusercontent.com/2480721/54346238-dae33a80-4655-11e9-9cf7-e81cc0bd2def.png)

2019-03-16 15:00 UTC, okayvlev commented
Пофиксил

2019-03-19 11:49 UTC, underoot commented on index.html
> +                <div class="search-text">
Уже вне зачета. Пропустил, но данный `div` должен быть инпутом!

2019-03-19 11:52 UTC, underoot approved these changes

2019-03-19 11:52 UTC, closed without merging