Кирилл Вахрушев, M3337
itmo2019/task2 pull request #35
Opened 2019-03-09 20:54 UTC by krikyn

2019-03-15 07:44 UTC, trixartem requested changes

2019-03-15 07:44 UTC, trixartem commented on index.css
> +    margin-left: calc(50% - 300px);
Почему именно такое число, на макете выглядит, как фиксированный отступ от логотипа

2019-03-15 07:44 UTC, trixartem commented on index.css
> +    margin-left: calc(50% - 300px);
search-box не выглядит как на макете

2019-03-15 07:44 UTC, trixartem commented on index.css
> +.in-button {
Семантически не понятное название

2019-03-15 07:44 UTC, trixartem commented on index.css
> +    color: white;
#fff

2019-03-15 07:44 UTC, trixartem commented on index.css
> +    font-style: normal;
Это же значения по умолчанию, их писать не обязательно

2019-03-15 07:44 UTC, trixartem commented on index.css
> +    cursor: pointer;
Можно просто сделать ссылкой, тогда не прийдется добавлять это свойство.

2019-03-15 07:44 UTC, trixartem commented on index.css
> +    cursor: pointer;
У кнопки по умолчанию стоит это свойство

2019-03-15 07:44 UTC, trixartem commented on index.css
> +    height: 22px;
Есть проблема, если текст будет слишком длинные, то слова будут переноситься и наезжать на элементы ниже

2019-03-15 07:44 UTC, trixartem commented on index.css
> +    color: #555555;
#555

2019-03-15 07:44 UTC, trixartem commented on index.css
> +    background-color: #ffffff;
Надо везде поправить на сокращенные

2019-03-15 07:44 UTC, trixartem commented on index.css
> +input[type="checkbox"] {
Его же можно идентифицировать по class или id

2019-03-15 07:44 UTC, trixartem commented on index.css
> +    visibility: hidden;
Если заранее заморачиваться за доступность, то лучше всего скрывать чекбокс таким способом
```css
  -moz-appearance: none;
  -webkit-appearance: none;
  appearance: none;
  position: absolute;
```
Вот подробное видео

2019-03-15 07:44 UTC, trixartem commented on index.css
> +img.mail-discription {
img точно нужен?

2019-03-15 07:44 UTC, trixartem commented on index.css
> +    font-stretch: normal;
Это же значения по умолчанию. Посмотри, пожалуйста, везде и убери лишнее

2019-03-15 07:44 UTC, trixartem commented on index.css
> +p.mail-discription {
Если добавить много текста, то верстка поедет

2019-03-15 07:44 UTC, trixartem commented on index.css
> +.close-button {
Этот контрол лучше позиционировать абсолютно, что бы никто не мог его подвинуть случайно

2019-03-15 07:44 UTC, trixartem commented on index.css
> +    float: right;
Если мало текста, то картинка вываливается за пределы родителя. Добавь clearFix

2019-03-16 14:00 UTC, krikyn commented on index.css
> +    cursor: pointer;
Я может что-то не так понял, но у кнопки вроде нету такого свойства по умолчанию.
https://ux.stackexchange.com/questions/105024/why-dont-button-html-elements-have-a-css-cursor-pointer-by-default

2019-03-16 14:11 UTC, krikyn commented on index.css
> +img.mail-discription {
Конечно, потому что у всех общие правила .mail-discription, а здесь конксретно для img - это лучше чем везде в класс впихивать еще одно название (и будет class="mail-discription mail-discription-img" )

2019-03-16 16:51 UTC, krikyn commented
Все исправил

2019-03-16 16:53 UTC, krikyn commented
Все исправил

2019-03-18 06:08 UTC, trixartem commented on index.css
> +    position: absolute;
👍

2019-03-18 06:09 UTC, trixartem commented on index.css
> +    overflow: auto;
Почти, я имел в виду вот этот подход 
https://htmlacademy.ru/courses/65/run/16

2019-03-18 06:43 UTC, trixartem requested changes
Код аккуратный, молодец!

Есть еще небольшие замечания:
- Если в теле письма много текста, то крестик скролится вместе с контентом
- При наведении на пункты меню, было бы круто видеть реакцию. Т.е. эффекты на hover
- Поиск немного не похож на тот что в макете
- Текст в подвале, обычно, ссылки

2019-03-23 15:50 UTC, krikyn commented
Все исправил

2019-03-25 17:00 UTC, trixartem commented
Задание выполнено, но на будущее, старайся делать максимально близко к макету

2019-03-25 17:00 UTC, closed without merging