Куриленко Влад, М3337
itmo2019/task2 pull request #36
Opened 2019-03-09 20:58 UTC by MadHypnofrog

2019-03-13 12:21 UTC, underoot requested changes
* Указанные замечания
* При очень маленьком разрешении экрана едет верстка. Надо предусмотреть это
* Стоит обратить внимание на несоответствиям макетам: типы шрифтов, отступы в списке писем, размер инпута поиска и пр.
* Также обратить внимание на требования, которые оглашали в чате:

> Типичные ошибки выполнения задания №2, для исправления которых можно не ждать менторов: 
> 1. Везде может быть любой текст и любое его количество, от кнопок управления письмом, до поля с датой 
> 2. Отступы, шрифты, размеры. Многие пропускают шрифты в футере и делают неверные отступы в левом меню 
> 3. Логотип лучше сделать png/svg, чем transform найденного yandex sans 
> 4. Семантика элементов управления – это ссылки и они должны показывать что-то по наведению 
> 5. Многие не понял что означает буковка Я и синий кружок. Буковка Я – это логотип сервиса, в данном случае Яндекса, его может не быть или он может быть совершенно другой. Синий кружочек – это маркер прочитанности письма.

2019-03-13 12:21 UTC, underoot commented on styles.css
> +	font-size: 24px;
Отступы в файле привести в порядок следует

2019-03-13 12:21 UTC, underoot commented on task2.html
> +			<div id="logo">
Стилизацию с использованием идентификаторов стоит сводить к минимум. Стоит использовать классы

2019-03-13 12:21 UTC, underoot commented on styles.css
> +.letter_element {
Что-то здесь не так

2019-03-13 12:21 UTC, underoot commented on styles.css
> +.bullet {
Это не просто булет, это пометка о непрочитанном сообщений. Больше семантики!

2019-03-16 18:10 UTC, MadHypnofrog commented on styles.css
> +	font-size: 24px;
саблайм пошалил видимо

2019-03-16 18:10 UTC, MadHypnofrog commented on task2.html
> +			<div id="logo">
поменял на классы все

2019-03-16 18:10 UTC, MadHypnofrog commented on styles.css
> +.letter_element {
действительно, удалил

2019-03-16 18:10 UTC, MadHypnofrog commented on styles.css
> +.bullet {
добавил в название

2019-03-19 11:58 UTC, underoot commented on task2.html
> +						<svg xmlns="http://www.w3.org/2000/svg" class="header__yandex_image"><svg id="svgicon-boot--Yandex_ru"><title xmlns="http://www.w3.org/2000/svg">Artboard 3</title><g xmlns="http://www.w3.org/20
Если манипуляции с SVG не нужны, то проще встроить `img`

2019-03-19 11:58 UTC, underoot commented on styles.css
> +@font-face {
Не подключил Яндексовый шрифт макетный, но это не критично

2019-03-19 12:00 UTC, underoot approved these changes

2019-03-19 12:00 UTC, closed without merging