Done
itmo2019/task2 pull request #39
Opened 2019-03-09 21:02 UTC by sandrafox

2019-03-12 11:11 UTC, mokhov commented
@sandrafox напишите ФИ и группу

2019-03-13 19:42 UTC, sandrafox commented
Александра Лисицына, М3335

2019-03-14 09:54 UTC, underoot requested changes
![image](https://user-images.githubusercontent.com/2480721/54346516-43321c00-4656-11e9-9fb0-180089cb9997.png)

Стоит привести содержимое к макету для начала

2019-03-19 11:55 UTC, underoot commented
![image](https://user-images.githubusercontent.com/2480721/54604099-0485d280-4a57-11e9-9cae-bcd729f902ca.png)
Стало определенно лучше, но от макета достаточно далеко

2019-05-15 09:25 UTC, closed without merging