Дугинец Никита M3337 hw2
itmo2019/task2 pull request #4
Opened 2019-03-08 22:06 UTC by glcanvas

2019-03-13 10:56 UTC, underoot requested changes
По указанным замечаниям нужны правки. Кроме того, концептуально:
* Усложнена структура верстки. Слишком много необоснованно использованных `float` и всяческие хаки в стиле `overflow: hidden`
* Классы названы не семантично. Неплохо бы следовать хотя бы базовым правилам наименования: использовать более подходящие названия для узлов, чтобы было понятно лишь из одного названия что это; избегать использования значений, позиции и прочих стилей в названии (например `not-more-147px`, `inner`)
* Также стоит обратить внимания на требования, оглашенные в чате

2019-03-13 10:56 UTC, underoot commented on index.html
> +<head>
Неплохо бы хотя бы `<title>` странице обрести

2019-03-13 10:56 UTC, underoot commented on index.html
> +<html>
`doctype` [необходимая](https://html.spec.whatwg.org/multipage/syntax.html#the-doctype) преамбула!

2019-03-13 10:56 UTC, underoot commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Довольно спорный момент, но желательно изначально прятать конфигурационные файлы свой IDE за своими [глобальными настройками](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreexcludesFile) игнора в Git. Хотя существуют командные практики, при которых настройки IDE шарятся.

2019-03-13 10:56 UTC, underoot commented on index.html
> +            <div class="new-mail">
Кнопка должна оставаться кнопкой

2019-03-13 10:56 UTC, underoot commented on style.css
> +main * {
Очень плохая практика. Отступы стоит настраивать индивидуально.

2019-03-13 10:56 UTC, underoot commented on navigations.css
> +    font-family: HelveticaNeueMedium;
Неплохо бы указать _fallback_

2019-03-13 10:56 UTC, underoot commented on index.html
> +            <div class="multy-lines">
А ведь можно было бы обойтись тремя элементами для этого. А есть если вспомнить про псевдо-элементы, то и вообще одним.

2019-03-13 10:56 UTC, underoot commented on index.html
> +            <div class="multy-lines">
_Бургер_, на вид, не особенно относится к логотипу. Скорее это семантично отдельный элемент интерфейса

2019-03-13 10:56 UTC, underoot commented on style.css
> +    display: block;
Зачем блочному элементу говорить, что он блочный

2019-03-13 10:56 UTC, underoot commented on style.css
> +    width: 800px;
Интерфейс должен быть адаптивным, то есть тянуться в зависимости от разрешения экрана. Сейчас интерфейс имеет фиксированные размеры, при котором на маленьком экране необходимо скролить, а на большом — лицезреть незанятое пространство

2019-03-13 10:56 UTC, underoot commented on style.css
> +    height: 100%;
Это зачем?

2019-03-13 10:56 UTC, underoot commented on index.html
> +<div class="background">
Название обманчивое. Это же не фон даже

2019-03-13 10:56 UTC, underoot commented on index.html
> +                <p>Яндекс</p>
Можно было бы использовать какой-нибудь _инлайн_-элемент и не пришлось бы притворяться, что он он _инлайн_

2019-03-13 10:56 UTC, underoot commented on index.html
> +                    <label for="is-active-essay" style="width: 100%; height: 100%; position: absolute;"></label>
Когда я кликаю на _checkbox_ первого письма, то мне открывается письмо, а _checkbox_ не меняет состояние

2019-03-13 10:56 UTC, underoot commented on index.html
> +                <div class="clear-button">x</div>
Иконка очистки инпута явно не по макету

2019-03-13 10:56 UTC, underoot commented on index.html
> +                <div class="input not-more-147px">
`not-more-147px` довольно странное название для класса. А если значение когда-нибудь изменится? Придется везде менять название класса

2019-03-13 10:56 UTC, underoot commented on headers.css
> +    background-color: #f2f5f8;
Можно было бы сделать просто прозрачным

2019-03-13 10:56 UTC, underoot commented on headers.css
> +    font-family: "YS Text - Regular", serif;
Во-первых, такого шрифта у тебя не настроено. Во-вторых, браузерные стили _одержат верх_ над этими, поскольку объявлены на узле-обертке

2019-03-13 10:56 UTC, underoot commented on headers.css
> +.input-placeholder div {
Стоит уточнить класс дочернего узла

2019-03-13 10:56 UTC, underoot commented on index.html
> +                <input placeholder="Поиск">
Отступ текста не по макету

2019-03-13 10:56 UTC, underoot commented on headers.css
> +    overflow: hidden;
Для чего?

2019-03-13 10:56 UTC, underoot commented on headers.css
> +.yandex-logo .yandex-name * {
Для двух элементов универсальный селектор выглядит лишним

2019-03-13 10:56 UTC, underoot commented on index.html
> +            <div class="input-placeholder">
Название `input-placeholder` путает и подразумевает именно _placeholder_, хотя по сути данный узел скорее обертка над инпутом

2019-03-13 10:56 UTC, underoot commented on index.html
> +    <div class="header">
В HTML есть даже специальный семантичный тег `<header>`

2019-03-13 10:56 UTC, underoot commented on index.html
> +        <div class="navigate">
`navigate` больше похоже на глагол, нежели чем на название сущности. В HTML есть специальный тег для разметки навигации (`<nav>`)

2019-03-13 10:56 UTC, underoot commented on index.html
> +                <div>
Зачем эта дополнительная обертка?

2019-03-13 10:56 UTC, underoot commented on index.html
> +            <div class="new-mail">
Странно, что внутри навигации появился не пункт навигации, а отдельное действие _Написать письмо_. Выглядит несемантично

2019-03-13 10:56 UTC, underoot commented on index.html
> +                <div class="input not-more-147px">
А зачем нужен класс `input`?

2019-03-13 10:56 UTC, underoot commented on index.html
> +            <div class="hover-select">
Называть класс по названию события с точки зрения семантики вредно. Стоит придумать название сущности, например `navigation-item`, а внутри `navigation-item-text`

2019-03-13 10:56 UTC, underoot commented on index.html
> +                <div class="output not-more-147px">
А для чего класс `output`?

2019-03-13 10:56 UTC, underoot commented on navigations.css
> +    height: 598px;
А зачем устанавливаешь значение высоты?

2019-03-13 10:56 UTC, underoot commented on navigations.css
> +    display: inline;
А почему не оставил его блочным?

2019-03-13 10:56 UTC, underoot commented on navigations.css
> +    text-overflow: ellipsis;
Ты же внутри пунктов навигации такое правило установил?

2019-03-13 10:56 UTC, underoot commented on navigations.css
> +.hover-select:hover {
Неплохо бы модифицировать тип курсора при наведении

2019-03-13 10:56 UTC, underoot commented on navigations.css
> +    float: left;
Это объявление уже установлено в `.hover-select`

2019-03-13 10:56 UTC, underoot commented on navigations.css
> +.hover-select div, .hover-select:hover div {
Неплохо бы уточнить класс дочернего элемента

2019-03-13 10:56 UTC, underoot commented on navigations.css
> +.hover-select div, .hover-select:hover div {
Зачем дублировать правила для псевдоселектора `:hover`? Кажется, что `.hover-select:hover` остается `.hover-select` также

2019-03-13 10:56 UTC, underoot commented on navigations.css
> +     text-indent: 1em;
Что-то здесь с отступом случилось (я про форматирование в данном файле)

2019-03-13 10:56 UTC, underoot commented on navigations.css
> +    margin: 4px 0 4px 0;
Можно было бы короче:
```
margin: 4px 0;
```

2019-03-13 10:56 UTC, underoot commented on style.css
> +body {
Еще неплохо было бы сбросить стили браузерные (`margin: 0`)

2019-03-13 10:56 UTC, underoot commented on style.css
> +    margin: 10px 0 0 0;
`margin-top: 10px`

2019-03-13 10:56 UTC, underoot commented on style.css
> +    clear: both;
Зачем?

2019-03-13 10:56 UTC, underoot commented on index.html
> +        <div class="inner">
Внутри чего? Над семантикой названия класса стоит поработать

2019-03-13 10:56 UTC, underoot commented on mails.css
> +    float: top;
Такого значения у правила `float` нет. Объясни что ты хотел этим сделать?

2019-03-13 10:56 UTC, underoot commented on index.html
> +                <div>
Но ведь это же ссылки все-таки

2019-03-13 10:56 UTC, underoot commented on mails.css
> +.list-header * {
Стоит уточнить класс, а не использовать универсальный селектор

2019-03-13 16:40 UTC, glcanvas commented on index.html
> +            <div class="new-mail">
@underoot  что значит первый комментарий? т.е. при наведении на div надо менять стиль курсора?

2019-03-13 16:44 UTC, glcanvas commented on style.css
> +main * {
@underoot  т.е.? ctrl + alt + shift + l -- дали мне отформатированный код

2019-03-13 17:23 UTC, glcanvas commented on headers.css
> +    overflow: hidden;
что бы не было так:
![image](https://user-images.githubusercontent.com/22433265/54300383-cbb8aa00-45cd-11e9-9114-84a22e1db221.png)

2019-03-13 17:46 UTC, glcanvas commented on navigations.css
> +    text-overflow: ellipsis;
последние три да

2019-03-13 18:45 UTC, glcanvas commented on navigations.css
> +    font-family: HelveticaNeueMedium;
`Property 'fallback' is allowed only in following rules: @counter-style`
но я не использую `@counter-style`

2019-03-14 06:44 UTC, underoot commented on index.html
> +            <div class="new-mail">
Нет, что это должен быть элемент `<button>`

2019-03-14 06:44 UTC, underoot commented on style.css
> +main * {
Я про то, что в HTML отдельным элементам нужно настраивать `margin`, а не выставить везде и где-то сбрасывать

2019-03-14 06:46 UTC, underoot commented on mails.css
> +.list-footer a {
Уточни класс, чтобы не зависеть от тега

2019-03-14 06:47 UTC, underoot commented on navigations.css
> +    font-family: HelveticaNeueMedium;
Под _fallback_-ом я подразумевал альтернативный шрифт в списке

2019-03-14 06:49 UTC, underoot commented on headers.css
> +    overflow: hidden;
Стоит подумать/переверстать так, чтобы избегать таких _хаков_

2019-03-14 21:20 UTC, glcanvas commented
@underoot  готово, поправил

2019-03-15 13:45 UTC, underoot commented on index.html
> +    <div class="yandex-logo-title">
Еще осталось логотип привести в порядок (п.3 из замечаний из списка в чате):
> Типичные ошибки выполнения задания №2, для исправления которых можно не ждать менторов: 
> 1. Везде может быть любой текст и любое его количество, от кнопок управления письмом, до поля с датой 
> 2. Отступы, шрифты, размеры. Многие пропускают шрифты в футере и делают неверные отступы в левом меню 
> 3. Логотип лучше сделать png/svg, чем transform найденного yandex sans
> 4. Семантика элементов управления – это ссылки и они должны показывать что-то по наведению 
> 5. Многие не понял что означает буковка Я и синий кружок. Буковка Я – это логотип сервиса, в данном случае Яндекса, его может не быть или он может быть совершенно другой. Синий кружочек – это маркер прочитанности письма.

2019-03-15 13:47 UTC, underoot commented on mails-placeholder.css
> +.mail-placeholder-list-of-mails .readed .mail-message {
В качестве рекомендации. Не стоит использовать глубокую вложенность селекторов, поскольку их сложно поддерживать

2019-03-15 15:44 UTC, glcanvas commented
@underoot поправил заголовок почты

2019-03-16 12:07 UTC, underoot commented
Есть еще пока небольшие расхождения с макетом: размер шрифта, цвет разделителей между письмами и футером, положение элементов интерфейса некоторых (например крестик к инпуте)

2019-03-16 13:34 UTC, glcanvas commented
@underoot , кажется, готово

2019-03-19 11:40 UTC, underoot approved these changes

2019-03-19 11:40 UTC, closed without merging