Савон Юлия М3337
itmo2019/task2 pull request #40
Opened 2019-03-09 21:07 UTC by Tiloaria

2019-03-18 08:54 UTC, evgenymarkov requested changes
Почта отображается на полный экран, это гуд. Но нужно поработать над деталями: что должно быть кликабельно сделать кликабельным, ссылки сделать ссылками. Также что-то со шрифтом, у меня показывается системный с засечками, но явно задумывалось не так.

2019-03-18 08:54 UTC, evgenymarkov commented on .idea/HW2.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Файлы настроек IDE лучше не хранить в репозитории. Они зачастую специфичны для конкретного разработчика. Чтобы проблему решить сделать нужно следующее:

1) Добавить `.idea/` в `.gitignore`
2) Удалить из индекса git (но не с файловой системы) директорию `.idea`.
3) Сделать коммит с удалением файлов и запушить его.

2019-03-18 08:54 UTC, evgenymarkov commented on Yandex_front.html
> +<!DOCTYPE html>
Файл с разметкой главной страницы проекта принято называть `index.html`. Этому соглашению следуют и веб-серверы, которые при обращении, к примеру, на `/`, пытаются найти `/index.html` в файловой системе.

2019-03-18 08:54 UTC, evgenymarkov commented on Yandex_front.html
> +        <img src="Yandex_logo.jpg" alt="logo">
Для логотипов и иконок SVG подходит лучше, можно вытянуть их с настоящей почты из DevTools

2019-03-18 08:54 UTC, evgenymarkov commented on Yandex_front.html
> +    <div class="header_Yandex">
Лучше не смешивать camelCase и snake_case в именованиях классов, именах файлов, а писать единообразно

2019-03-18 08:54 UTC, evgenymarkov commented on Yandex_front.html
> +    <div class="search_rectangle">
Поиск – это не прямоугольник, поисковая строка – не `div`, кнопка закрытия/очистки поисковой строки – тоже не `div`. Нужно поработать над семантикой и неймингом.

2019-03-18 08:54 UTC, evgenymarkov commented on Yandex_front.html
> +        <div class="write">Написать</div>
Времена div'ной вёрстки прошли, нужно использовать все возможности HTML какие доступны. Оставляй `div` и `span` на случай когда не нашлось другого более подходящего элемента. Для "Написать" более подходящим является button.

2019-03-18 08:54 UTC, evgenymarkov commented on Yandex_front.html
> +    <div class="menu">
Похоже не на `div`, а на `nav`

2019-03-18 08:54 UTC, evgenymarkov commented on Yandex_front.html
> +        <div class="folders">
`ul` и `li`

2019-03-18 08:54 UTC, evgenymarkov commented on Yandex_front.html
> +            <div class="chosen">Входящие</div>
Можно было, к примеру, сделать общий класс `folder` для всех папок с письмами, а для текущего заиспользовать два класса `folder` и `folder_chosen`.

2019-03-18 08:54 UTC, evgenymarkov commented on Yandex_front.html
> +        <div class="divider"></div>
Чтобы делать разделители не обязательно добавлять элементы в DOM. Для этого достаточно поиграться со свойством `border` в CSS.

2019-03-18 08:54 UTC, evgenymarkov commented on Yandex_front.html
> +                    <div class="message_unread">Доступ к аккаунту восстановлен</div>
Опять же рекомендую пользоваться возможностью писать несколько классов для элементов, тогда `message_unread` и `message_read` могут быть заменены на `message` и `message_unread`, где для `message_unread` просто добавляются стили, которых не хватает в `message` для индикации того, что сообщение не прочитано.

2019-03-18 08:54 UTC, evgenymarkov commented on Yandex_front.html
> +            <div class="divider"></div>
Разделители везде сделай с помощью свойства `border` в CSS. Чем меньше элементов в DOM, тем более производительным будет твой сайт.

2019-03-18 08:54 UTC, evgenymarkov commented on Yandex_front.html
> +
Не оставляй пустые строки. Голый HTML, который не прогонялся ни через какие минификаторы, шаблонизаторы и системы сборки, содержит в себе переносы строк, пробелы, которые в вёрстке показываются и могут привести к появлению неожиданных артефактов и непонятно откуда взявшихся лишних отступов. React с его JSX такой проблеме не подвержен, минифицированный HTML тоже.

2019-03-18 08:54 UTC, evgenymarkov commented on Yandex_front.html
> +                <div class="item">Помощь и обратная связь</div>
Это должны быть ссылки, а не div'ы

2019-03-18 08:54 UTC, evgenymarkov commented on style.css
> +    font-family: 'Yandex Sans Display', Serif, serif;
Yandex Sans – шрифт без засечек. Ты указываешь в качестве fallback'а шрифты с засечками. Наиболее близкий по начертанию к YS шрифт это Arial, а потом уже идут различные системные sans-serif'ы.
К чему это может привести? Если Yandex Sans не загрузится или загрузится позже, пользователь будет видеть сайт с совершенно другой типографикой.

2019-03-18 08:54 UTC, evgenymarkov commented on style.css
> +    font-size: xx-large;
Лучше указывать значения в `px`.

2019-03-18 08:54 UTC, evgenymarkov commented on style.css
> +    color: #000000;
Можно и нужно сокращать до короткой hex записи такие цвета (`#000`)

2019-03-18 08:54 UTC, evgenymarkov commented on style.css
> +    color: #555555;
`#555`

2019-03-18 08:54 UTC, evgenymarkov commented on style.css
> +header {
Селекторы по тэгам и по id лучше не писать, а всегда для стилизации использовать классы

2019-03-18 08:54 UTC, evgenymarkov commented on Yandex_front.html
> +        <img src="Yandex_logo.jpg" alt="logo">
Гамбургер, логотип компании и логотип сервиса – разные элементы

2019-03-21 01:37 UTC, Tiloaria commented
@evgenymarkov замечания исправлены

2019-03-25 14:25 UTC, evgenymarkov approved these changes

2019-03-25 14:26 UTC, closed without merging