Крылов Дмитрий. М3337
itmo2019/task2 pull request #41
Opened 2019-03-09 21:51 UTC by nibydlo

Отправил еще в 6 вечера, но неправильным способом, надеюсь на дедлайн не скажется.

2019-03-15 19:17 UTC, mokhov requested changes
В чате есть информация о типичных ошибках, которые стоит поправить, дублирую сюда:
Типичные ошибки выполнения задания №2, для исправления которых можно не ждать менторов:
1. Везде может быть любой текст и любое его количество, от кнопок управления письмом, до поля с датой
2. Отступы, шрифты, размеры. Многие пропускают шрифты в футере и делают неверные отступы в левом меню
3. Логотип лучше сделать png/svg, чем transform найденного yandex sans
4. Семантика элементов управления – это ссылки и они должны показывать что-то по наведению
5. Многие не понял что означает буковка Я и синий кружок. Буковка Я – это логотип сервиса, в данном случае Яндекса, его может не быть или он может быть совершенно другой. Синий кружочек – это маркер прочитанности письма.

Сейчас результат сильно отличается от макета (в том числе некоторые элементы уезжают)

2019-03-15 19:20 UTC, mokhov commented
![Входящие - Яндекс Почта 2019-03-15 22-15-46](https://user-images.githubusercontent.com/357689/54456711-81bbf980-4770-11e9-8d17-6c661e8270b0.jpg)

2019-03-23 03:49 UTC, mokhov commented
При сжимании всё разъезжается
![Входящие - Яндекс Почта 2019-03-23 06-48-49](https://user-images.githubusercontent.com/357689/54861283-c5e26780-4d37-11e9-888e-14d0524c4e61.jpg)

2019-03-23 03:51 UTC, mokhov commented
![Входящие - Яндекс Почта 2019-03-23 06-50-31](https://user-images.githubusercontent.com/357689/54861300-fa562380-4d37-11e9-94f4-06f56492c31f.jpg)
Это есть в типичных ошибках. В FF скриншот выше, в яузере это распирает контейнер :(

2019-03-23 03:51 UTC, mokhov commented
Я вижу что комментарий про типичные ошибки по большей части проигнорирован

2019-03-23 05:11 UTC, nibydlo commented
> ![Входящие - Яндекс Почта 2019-03-23 06-50-31](https://user-images.githubusercontent.com/357689/54861300-fa562380-4d37-11e9-94f4-06f56492c31f.jpg)
> Это есть в типичных ошибках. В FF скриншот выше, в яузере это распирает контейнер :(

Эмм, в чем может быть проблема, если у меня в хроме все прекрасно сжималось и работало?
min-width: max-content поддерживается в яузере?

P.S. типичные ошибки не проигнорены

2019-03-23 09:49 UTC, nibydlo commented
> ![Входящие - Яндекс Почта 2019-03-23 06-50-31](https://user-images.githubusercontent.com/357689/54861300-fa562380-4d37-11e9-94f4-06f56492c31f.jpg)
> Это есть в типичных ошибках. В FF скриншот выше, в яузере это распирает контейнер :(

![Screenshot from 2019-03-23 12-47-13](https://user-images.githubusercontent.com/33055098/54864547-e6c3b080-4d69-11e9-9f57-2c834a80c1c8.png)
![Screenshot from 2019-03-23 12-45-06](https://user-images.githubusercontent.com/33055098/54864550-e9260a80-4d69-11e9-88fb-5229120b837a.png)

Собственно вот 2 скрина показать, что как добавление большого количества текста, так и сжатие окна не коробит ситуацию

Скорее всего дело в max-content, сегодня Артем, читавший лекцию, пояснил что этой константой лучше не пользоваться, так что исправлю.

2019-03-23 10:06 UTC, nibydlo commented
![Screenshot from 2019-03-23 13-04-40](https://user-images.githubusercontent.com/33055098/54864724-5470dc00-4d6c-11e9-8d05-98e253c244b9.png)
![Screenshot from 2019-03-23 13-04-25](https://user-images.githubusercontent.com/33055098/54864725-576bcc80-4d6c-11e9-8223-62bc526a3952.png)
Потестил в яузере, тоже все топчик сжимается.

На каком браузере тестить, чтобы сломать?)

2019-03-25 17:11 UTC, mokhov commented
Не вижу фикса в FF

2019-03-25 17:11 UTC, mokhov commented
> Эмм, в чем может быть проблема, если у меня в хроме все прекрасно сжималось и работало?
min-width: max-content поддерживается в яузере?

Много текста

2019-04-06 07:25 UTC, closed without merging