Макеев Петр, M3337
itmo2019/task2 pull request #42
Opened 2019-03-10 00:18 UTC by Good-Morning

2019-03-15 12:44 UTC, trixartem requested changes
Очень большие расхождения с макетом:
- Неправильный логотип
- Блок с письмами не тянется
- Шрифты с засечками
- Едет верстка, если в название поста вставлять длинный текст

2019-03-15 12:44 UTC, trixartem commented on index.html
> +                    <div></div>
Можно сделать одним элементом, использую ::after ::before

2019-03-15 12:44 UTC, trixartem commented on index.html
> +                <div id="menu">
Лучше использовать список

2019-03-15 12:44 UTC, trixartem commented on index.html
> +                        <div class="letter-menu-item">Переслать</div>
тоже лучше список

2019-03-15 12:44 UTC, trixartem commented on index.html
> +                            <div class="letter-date">6 авг</div>
Тег time

2019-03-15 12:44 UTC, trixartem commented on index.html
> +                        <footer style="text-align: right">Алюминевые огурцы - В.Цой</footer>
почему не в CSS?

2019-03-15 12:44 UTC, trixartem commented on styles.css
> +    background-color: #ffffff;
#fff

2019-03-15 12:44 UTC, trixartem commented on styles.css
> +    margin-left: -100%;
Лучше через position absolute. Так надежнее

2019-03-15 12:44 UTC, trixartem commented on styles.css
> +    padding: 7px 0px 0px 0px;
можно просто 0, без px

2019-03-15 12:44 UTC, trixartem commented on styles.css
> +    cursor: pointer;
pointer должен быть только при наведении

2019-03-15 12:44 UTC, trixartem commented on styles.css
> +    max-width: 40%;
почему не просто width:40% ?

2019-03-15 12:44 UTC, trixartem commented on styles.css
> +    float: left;
Если текста будет мало, то картинка выпадет за пределы блока. Используй clearFix

2019-03-16 06:27 UTC, stormtrooper1859 reviewed
Flex - ban

2019-03-16 06:27 UTC, stormtrooper1859 commented on styles.css
> +    display: flex;
Ban

2019-03-16 06:27 UTC, stormtrooper1859 commented on styles.css
> +    display: flex;
Ban

2019-03-16 06:27 UTC, stormtrooper1859 commented on styles.css
> +    display: flex;
Ban

2019-03-16 06:27 UTC, stormtrooper1859 commented on styles.css
> +    display: flex;
Ban

2019-03-16 06:27 UTC, stormtrooper1859 commented on styles.css
> +    display: flex;
Ban

2019-03-16 06:27 UTC, stormtrooper1859 commented on styles.css
> +    display: flex;
Ban

2019-03-16 18:40 UTC, Good-Morning commented on index.html
> +                        <footer style="text-align: right">Алюминевые огурцы - В.Цой</footer>
Это не вполне относится к верстке "почты" - скорее к содержанию письма.
Перенес в CSS.

2019-03-16 18:41 UTC, Good-Morning commented on styles.css
> +    cursor: pointer;
Это не понял - ничего не менял.

2019-03-16 18:49 UTC, Good-Morning commented
Логотип заменил картинкой.
Если я правильно понял, письма всегда тянулись. Разве что из эстетических соображений ширина была ограничена. Ограничение с 800px ослабил до 1000px.
Изменил шрифт на Helvetica, там засечек, вроде бы, нет.
Не понял в каком посте ехала верстка, но: display: flex все убрал, пофиксил поехавшую верстку, где нашел.

2019-03-20 06:05 UTC, trixartem commented on index.html
> +                        <footer style="text-align: right">Алюминевые огурцы - В.Цой</footer>
Лучше разделять ответственность:
HTML - разметка
CSS - стили
Такой принцип поможет легче поддерживать код в будущем

2019-03-20 06:17 UTC, trixartem requested changes
Есть 2 замечания:
1. Инпут не настоящий
2. Когда открывается письмо, то список писем наезжает на футер. И когда просто много писем, тоже наезжают. Они либо должны растягивать элемент, либо должен появляться скролл

2019-03-20 06:17 UTC, trixartem commented on index.html
> +                    <div class="search-field">Поиск</div>
Для поле ввода лучше использовать input, он по умолчанию интерактивный, а div нет

2019-03-20 06:17 UTC, trixartem commented on styles.css
> +    padding: 7px 4% 0 2%;
Почему отступы в процентах? Здесь не не предусматривается пропорциональное изменение отступов

2019-03-20 06:17 UTC, trixartem commented on styles.css
> +    font-family: Helvetica, sans-serif;
Можно же задать сразу всей странице

2019-03-20 06:17 UTC, trixartem commented on styles.css
> +    text-overflow: clip;
ellipsis?

2019-03-22 11:37 UTC, Good-Morning commented on styles.css
> +    text-overflow: clip;
ellipsis, если срабатывает, закрывает все содержимое, а text-overflow здесь нужен лишь для непредвиденных случаев (в т.ч. вписывание произвольного текста), чтобы обойтись малой кровью.

2019-03-25 17:08 UTC, trixartem commented
Задание выполнено

2019-03-25 17:08 UTC, closed without merging