Даминов Нодир М3339
itmo2019/task2 pull request #44
Opened 2019-03-21 23:24 UTC by DaminovN

Простите, но я на почту отправлял решение уложенное в первый дедлайн, так как в условии задания не было сказанно что принимаются только PR я увы не знал что по почте нельзя. Можете пожалуйста проверить ?

2019-03-25 13:00 UTC, mokhov commented
Дублирую комментарий из телеграма:
> Типичные ошибки выполнения задания №2, для исправления которых можно не ждать менторов:
1. Везде может быть любой текст и любое его количество, от кнопок управления письмом, до поля с датой
2. Отступы, шрифты, размеры. Многие пропускают шрифты в футере и делают неверные отступы в левом меню
3. Логотип лучше сделать png/svg, чем transform найденного yandex sans
4. Семантика элементов управления – это ссылки и они должны показывать что-то по наведению
5. Многие не поняли что означает буковка Я и синий кружок. Буковка Я – это логотип сервиса, в данном случае Яндекса, его может не быть или он может быть совершенно другой. Синий кружочек – это маркер прочитанности письма.

2019-03-25 13:01 UTC, mokhov requested changes
Дублирую комментарий из телеграма:
Типичные ошибки выполнения задания №2, для исправления которых можно не ждать менторов:
1. Везде может быть любой текст и любое его количество, от кнопок управления письмом, до поля с датой
2. Отступы, шрифты, размеры. Многие пропускают шрифты в футере и делают неверные отступы в левом меню
3. Логотип лучше сделать png/svg, чем transform найденного yandex sans
4. Семантика элементов управления – это ссылки и они должны показывать что-то по наведению
5. Многие не поняли что означает буковка Я и синий кружок. Буковка Я – это логотип сервиса, в данном случае Яндекса, его может не быть или он может быть совершенно другой. Синий кружочек – это маркер прочитанности письма.

2019-03-30 17:40 UTC, DaminovN commented
Я добавил исправления, я отправлял задачу во время первого дедлайна(на почту) и по сути проверили меня только один раз пока что(, признаю что это моя ошибка - не внимательность на лекции и прослушал то что нельзя на почту больше отпралять, я уже полный бал по задаче увы не получу ?(

2019-04-06 07:30 UTC, mokhov commented
![Яндекс Почта 2019-04-06 10-30-16](https://user-images.githubusercontent.com/357689
/55666387-002f2700-5857-11e9-98d7-19f1cb279918.jpg)

2019-04-06 07:33 UTC, mokhov requested changes
Ещё есть что доделать

2019-04-06 07:33 UTC, mokhov commented on index.html
> +            <img src="images/ya-mail-logo.png" alt="" class="page__ya-mail-logo" width="153" height="31">
А почему это не ссылка?

2019-04-06 07:33 UTC, mokhov commented on index.html
> +                    <img class="my-blog__round" src="images/round.png" width="400" height="400">
В тексте письма у картинки обязательно должен быть `alt`

2019-04-06 07:33 UTC, mokhov commented on style.css
> +    font-family: YandexSansBold;
У bold лучше всегда указывать что это `font-weight: 700`

2019-04-07 23:18 UTC, DaminovN commented
@mokhov Добавил исправления

2019-04-20 12:47 UTC, closed without merging