Homework №2, Kokorin Ilya, M3339
itmo2019/task2 pull request #5
Opened 2019-03-09 08:47 UTC by KokorinIlya

2019-03-13 09:39 UTC, rmbaad requested changes
В первую очередь надо переверстать всё с абсолютов на обычное позиционирование элементов. Так же вёрстка не резиновая, не тянется и не приспособлена для этого. Логотип не по макету. + все остальные комментарии по коду

2019-03-13 09:39 UTC, rmbaad commented on src/style.css
> +    position: absolute;
Здесь не нужен absolute, всё это можно сделать просто отступами родительского блока например (его можно добавить, если нет)

2019-03-13 09:39 UTC, rmbaad commented on src/style.css
> +    list-style-type: none;
Для всех списков по умолчанию точно не стоит убирать буллеты

2019-03-13 09:39 UTC, rmbaad commented on src/style.css
> +    position: absolute;
Плохая практика делать positon absolute для body, да и непонятно зачем. body не должен абсолютно позиционироваться, он и есть родительских блок

2019-03-13 09:39 UTC, rmbaad commented on src/style.css
> +main {
Опять определение стилей для тега. Так делать не стоит

2019-03-13 09:39 UTC, rmbaad commented on src/style.css
> +#search-cross {
Почему не класс?

2019-03-13 09:39 UTC, rmbaad commented on src/style.css
> +    left: 580px;
А что если поле будет длиннее? Лучше позиционировать от другого края

2019-03-13 09:39 UTC, rmbaad commented on src/style.css
> +    opacity: 0.15;
Можно задать курсор, чтобы при наведении было понятно что оно в теории кликабельно

2019-03-13 09:39 UTC, rmbaad commented on src/style.css
> +#all-letters {
Почему не класс?

2019-03-13 09:39 UTC, rmbaad commented on src/style.css
> +#all-letters {
Больше бы подошло название сущности, что-то вроде letters-list

2019-03-13 09:39 UTC, rmbaad commented on src/style.css
> +    position: absolute;
Всю вёрстку которая присутствует, можно вполне делать без абсолютов, позиционируя отступами. В противном случае будет очень сложно делать резиновость и вообще поддерживать такую вёрстку

2019-03-13 09:39 UTC, rmbaad commented on src/style.css
> +#search {
Опять id

2019-03-13 09:39 UTC, rmbaad commented on src/style.css
> +    opacity: 0.5;
Из-за opacity будет прозрачным не только фон блока, но и его содержимое (в данном случае текст) что не очень читабельно и отличается от макета

2019-03-13 09:39 UTC, rmbaad commented on src/style.css
> +    position: absolute;
Нужно убрать все абсолюты, они тут не нужны

2019-03-13 09:39 UTC, rmbaad commented on src/style.css
> +    vertical-align: middle;
Это свойство не работает для блочных элементов. Так же ниже по коду

2019-03-13 09:39 UTC, rmbaad commented on src/style.css
> +.sender-read {
У тебя есть два класса — sender и sender-read которые по большей части повторяют друг друга и собственно они для одной и той же сущности но в разных состояниях. Ты можешь всем отправителям поставить класс sender, а свойство которое отвечает за прочитанность (в данном случае шрифт) менять другим классом. Например в html `<div class="sender sender-read">` и соответственно в классе sender-read переопределить только шрифт

2019-03-13 09:39 UTC, rmbaad commented on src/style.css
> +    border-radius: 10px;
Чтобы радиус не зависел от размера, можно просто сделать его 50%

2019-03-13 09:39 UTC, rmbaad commented on src/style.css
> +    max-width: 250px;
Не очень понятно зачем здесь и в остальных стилях max-width и max-height, т.к. вёрстка не тянется и соответственно эти свойства ни на что не влияют

2019-03-13 09:39 UTC, rmbaad commented on src/style.css
> +#norma {
Непонятное имя селектора

2019-03-13 09:39 UTC, rmbaad commented on src/style.css
> +#bottom-links {
Опять же id ни к чему. Позиционирование не выглядит как на макете, и шрифт тоже

2019-03-13 09:39 UTC, rmbaad commented on src/index.html
> +                <div id="make-new-letter"><a>Написать</a></div>
Если это кнопка, то она должна быть button. В противном случае, у такого элемента не будет никакой интерактивности при пользовательском взаимодействии (кнопка нажимабельна, у неё есть несколько состояний, что позволяет пользователю понимать что его действия получают отклик) плюс люди с ограниченными возможностями не смогут распознать что это кнопка

2019-03-13 09:39 UTC, rmbaad commented on src/index.html
> +                    <li class="folders-choosing"><a>Входящие</a></li>
Ссылки без href некликабельные

2019-03-13 15:23 UTC, KokorinIlya commented on src/style.css
> +#norma {
Ну, там же отрывок из "Нормы" Сорокина

2019-03-13 15:50 UTC, KokorinIlya commented on src/style.css
> +    position: absolute;
Родительский класс для него это body, и отступы я делаю от него

2019-03-13 15:51 UTC, KokorinIlya commented on src/style.css
> +    position: absolute;
Чтобы дочерние блоки с position : absolute позиционировались относительно body

2019-03-16 10:16 UTC, KokorinIlya commented
@rmbaad, я переписал, можете посмотреть?

2019-03-16 14:46 UTC, rmbaad requested changes

2019-03-16 14:46 UTC, rmbaad commented on src/style.css
> +  padding-left: 22px;
Можно объединить в одно свойство padding

2019-03-16 14:46 UTC, rmbaad commented on src/style.css
> +  display: inline-block;
Эти два свойства противоречат друг другу, они оба про позиционирование. Надо выбрать что-то одно, и лучше чтобы это был не position absolute. Здесь вполне можно обойтись display inline-block, т.к. все блоки идут друг за другом

2019-03-16 14:46 UTC, rmbaad commented on src/style.css
> +  box-shadow: inset 0 0 0 1px rgba(0, 0, 0, 0.2);
zeplin не всегда предоставляет именно те стили, которые будут так же выглядеть в вёрстке, он только пытается это сделать. сравни с макетом, кажется тут нет необходимости в box-shadow и можно обойтись бордером

2019-03-16 14:46 UTC, rmbaad commented on src/style.css
> +  float: left;
float сделан для текста. не критично, но можно так же сделать через display inline-block

2019-03-16 14:46 UTC, rmbaad commented on src/style.css
> +  display: table;
это хак для выравнивания, который давно не используют. можно просто сделать списком меню, а его элементам задать line-height равным высоте пункта меню, тогда текст будет с отступами сверху и снизу ровно по центру

2019-03-16 14:46 UTC, rmbaad commented on src/style.css
> +.left-menu-elem a {
не критично, но лучше просто для тега `a` внутри меню задать класс и использовать его. так будет нагляднее и быстрее

2019-03-16 14:46 UTC, rmbaad commented on src/style.css
> +  display: table-cell;
здесь так же можно сделать просто display inline-block и line-height и не пытаться заставить блочный элемент вести себя как таблица

2019-03-16 14:46 UTC, rmbaad commented on src/style.css
> +  position: relative;
это свойство тут лишнее

2019-03-16 14:46 UTC, rmbaad commented on src/style.css
> +  margin-right: 10px;
можно просто `margin: 0 10px;`

2019-03-16 14:46 UTC, rmbaad commented on src/style.css
> +  position: absolute;
Почему бы просто не сделать такой же блок в `display: inline-block;` и `text-align: right;`?

2019-03-16 14:53 UTC, rmbaad approved these changes
Считаю, что ты справился, но обрати внимание на комментарии, в будущем пригодится

2019-03-18 07:58 UTC, closed without merging