Рыкунов Николай M3335
itmo2019/task2 pull request #7
Opened 2019-03-09 09:51 UTC by Walingar

2019-03-15 15:56 UTC, Walingar commented
Нужно еще доделать `input`ы

2019-03-15 20:38 UTC, evgenymarkov requested changes
Лучше привести имена всех файлов  kebab-case и не смешивать

Тест на переполнение контентом прошёл. В нейминге классов стремишься к БЭМу, но пока не всё идеально. В качестве разделителя слов в блоке и элементе в лучше использовать - а не _.

2019-03-15 20:38 UTC, evgenymarkov commented on src/css/font/demo.html
> +<!DOCTYPE html>
Зачем этот документ? Он не является решением задачи. Также добавлено огромное количество шрифтов во всех возможных форматах, которые, по факту, не нужны.

В современном вебе, если не требуется поддержка старых браузеров, нужно подключать лишь шрифты в формате `.woff2`, если нужна поддержка IE11, то ещё и `.woff`.

Рекомендую прибраться и удалить всё ненужное.

2019-03-15 20:38 UTC, evgenymarkov commented on src/css/font/demo.html
> +<!DOCTYPE html>
[Про оптимизацию шрифтов](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization?hl=ru)

2019-03-15 20:38 UTC, evgenymarkov commented on src/index.html
> +  <link href="css/styles.css" rel="stylesheet">
Есть [рекомендованный порядок элементов](https://stackoverflow.com/a/26505680) в head и лучше ему следовать.

2019-03-15 20:38 UTC, evgenymarkov commented on src/index.html
> +<!DOCTYPE HTML>
Интересный вариант, но рекомендую остановиться на `<!DOCTYPE html>`, он более привычен разработчикам

2019-03-15 20:38 UTC, evgenymarkov commented on src/index.html
> +
Не оставляй пустые строки, код они не украшают

2019-03-15 20:38 UTC, evgenymarkov commented on src/index.html
> +        <img class="main_title_left" src="img/YandexLogoLeft.png">
Для логотипов и иконок SVG подходит лучше, можно вытянуть их с настоящей почты из DevTools

2019-03-15 20:38 UTC, evgenymarkov commented on src/index.html
> +        <div class="menu_icon_line"></div>
Лучше использовать SVG иконки, чем пытаться с помощью CSS повторить те или иные фигуры.

Подробнее о способах подключения svg можно почитать здесь
https://css-tricks.com/using-svg/

Вкратце опишу тут

Способы подключения SVG:

1) В CSS указать `url('url картинки или путь до файла')`
2) Подключить через `<img src="..." />`
3) Подключить через object: `<object type="image/svg+xml" data="url или путь до файла"> </object>`
4) Вставить в HTML как есть: `<body> <svg ...> ... </svg> </body>`

4 способ хорош, можно стилизовать и мучать эту svg'шку как душе угодно.

Но минус в том, что если SVG занимает, к примеру, 5 килобайт, то ты всегда эти 5 килобайт будешь загружать, потому что это часть разметки. Но если тебе не нужна гибкость, а просто векторная картинка, которая всегда одна и та же, а логотип таковой и является, то лучше подключить через 1, 2 или 3 способ и тогда браузер единожды загрузит эту картинку, а потом будет брать из кэша.

2019-03-15 20:38 UTC, evgenymarkov commented on src/index.html
> +          <div class="message" id="first_email">
Воспользуйся БЭМ модификатором вместо id

2019-03-15 20:38 UTC, evgenymarkov commented on src/index.html
> +            <time class="message_date" datetime="2019.02.20">20 фев</time>
Значение атрибута `datetime` нужно задавать в формате ISO8601.

http://htmlbook.ru/html/time/datetime

2019-03-15 20:38 UTC, evgenymarkov commented on src/index.html
> +<main>
Есть мысль, что основной контент страницы – список писем. Фиксить не призываю если мнение расходится.

2019-03-15 20:38 UTC, evgenymarkov commented on src/index.html
> +          <div class="main_menu_write">Написать</div>
В интерфейсе это выглядит как кнопка, значит кнопкой в разметке она и должна быть. Мало достигнуть соответствующего внешнего вида и поведения элемента, важно ещё сделать так чтобы твои намерения были поняты поисковым роботом, экранным диктором, а для того чтобы этого достичь нужно не забывать о семантике.

2019-03-15 20:38 UTC, evgenymarkov commented on src/index.html
> +            <div class="main_menu_li__text">Входящие</div>
По-моему внутренний div лишний, можно обойтись без него

2019-03-15 20:38 UTC, evgenymarkov commented on src/css/styles.css
> +#close_message_checkbox {
id лучше совсем не использовать для стилизации элементов

2019-03-15 20:38 UTC, evgenymarkov commented on src/css/styles.css
> +  -webkit-transform: rotate(45deg);
Префиксы вручную программисты обычно не пишут. За них это делают инструменты, например, `autoprefixer`.

2019-03-15 20:38 UTC, evgenymarkov commented on src/css/styles.css
> +  border: solid blue;
Цвета лучше записывать в hex представлении, в нижнем регистре и по возможности в сокращённой форме:

```
#fff
#f5f5dc
```

2019-03-15 20:38 UTC, evgenymarkov commented on src/css/styles.css
> +* {
Универсальный селектор не стоит использовать. Тебе достаточно было задать здесь `html`.

2019-03-15 20:38 UTC, evgenymarkov commented on src/css/styles.css
> +  font-family: HelveticaNeue, serif;
Почему именно HelveticaNeue? Если он встроен в Windows/macOS, это не значит, что он есть в других ОС. Установи для всех одинаковый кастомный шрифт, либо сделай хорошо всем выставив цепочку системных шрифтов.

https://css-tricks.com/snippets/css/system-font-stack/

2019-03-15 20:42 UTC, evgenymarkov reviewed
Оформление HTML немного поехало. Попробуй автоформаттеры кода. Наиболее крутой – Prettier.

2019-03-15 20:42 UTC, evgenymarkov commented on src/css/styles.css
> +  horiz-align: right;
Что это за правило такое? В спецификации отсутствует

2019-03-15 20:51 UTC, evgenymarkov reviewed
Строку поиска было бы неплохо стилизовать ещё, она сильно отличается от макета, а кнопка сброса содержимого улетела куда-то за пределы блока.

![image](https://user-images.githubusercontent.com/16443248/54461277-f2254380-478d-11e9-9d2b-c1b153af1782.png)

2019-03-16 13:07 UTC, Walingar commented on src/index.html
> +            <div class="main_menu_li__text">Входящие</div>
Без этого div ссылка только на текст получается(

2019-03-16 13:56 UTC, Walingar commented on src/index.html
> +          <div class="message" id="first_email">
Но я использую этот `id`, чтобы привязать к нему `label`

2019-03-19 07:28 UTC, evgenymarkov approved these changes

2019-03-19 07:28 UTC, closed without merging

2019-03-19 07:28 UTC, evgenymarkov commented
:fire: