Терещук Максим, М3335
itmo2019/task2 pull request #8
Opened 2019-03-09 09:56 UTC by teremax

2019-03-13 11:07 UTC, rmbaad requested changes

2019-03-13 11:07 UTC, rmbaad commented on src/style.css
> +#top {
Лучше без id там где это не нужно. Используй классы

2019-03-13 11:07 UTC, rmbaad commented on src/style.css
> +    position: absolute;
Можно спозиционировать без positon absolute

2019-03-13 11:07 UTC, rmbaad commented on src/style.css
> +    height: 2.4px;
Пиксель не должен быть дробным числом, это может неверно отображаться (как сейчас и есть)

2019-03-13 11:07 UTC, rmbaad commented on src/style.css
> +    position: absolute;
И ниже по коду тоже самое

2019-03-13 11:07 UTC, rmbaad commented on src/style.css
> +    position: absolute;
Нужно сверстать без position absolute вообще, здесь нет такой необходимости

2019-03-13 11:07 UTC, rmbaad commented on src/style.css
> +    background-color: #f2f4f7;
Не похоже на макет + нет крестика

2019-03-13 11:07 UTC, rmbaad commented on src/style.css
> +    float: left;
Можно сверстать без флоатов. Флоаты не для выравнивания, они для обтекания текста

2019-03-13 11:07 UTC, rmbaad commented on src/style.css
> +    height: 700px;
Если будет много писем, они не влезут в 700, это можно сделать минимальной высотой

2019-03-13 11:07 UTC, rmbaad commented on src/style.css
> +    width: 147px;
Бордер не как в макете

2019-03-13 11:07 UTC, rmbaad commented on src/style.css
> +#incoming {
Здесь и в других местах id не нужен, можно сделать классами

2019-03-13 11:07 UTC, rmbaad commented on src/style.css
> +#menu {
Меню тоже выглядит не как в макете. Отступы не те, размер кнопки не такой

2019-03-13 11:07 UTC, rmbaad commented on src/style.css
> +    width: 75%;
Будет неправильно масштабироваться. Лучше сделать отступы и задать 100%, тогда пропорции сохранятся

2019-03-13 11:07 UTC, rmbaad commented on src/style.css
> +    height: 30px;
Размеры/отступы не как в макете

2019-03-13 11:07 UTC, rmbaad commented on src/style.css
> +    position: absolute;
Нужно без position absolute. Здесь и везде, за исключением разве что крестика закрытия

2019-03-13 11:07 UTC, rmbaad commented on src/style.css
> +    left: 14%;
Вот как раз пример того, почему не стоит делать абсолютное позиционирование. Для добавления нового пункта меню придётся писать ещё один стиль, высчитывать его позиционирование. Если изменится текст пункта, придётся пересчитывать все позиции. Это очень непрактично и неудобно. Если бы они были простыми inline-блоками, было бы намного удобнее с ними работать

2019-03-13 11:07 UTC, rmbaad commented on src/style.css
> +    position: absolute;
То же самое

2019-03-13 11:07 UTC, rmbaad commented on src/style.css
> +.red_circle {
Текст в кружке не по центу по высоте

2019-03-13 11:07 UTC, rmbaad commented on src/style.css
> +.blue_circle {
А если завтра решат перекрасить, придётся менять и название класса в css и в html. Названия должны отражать сущность, а не какие-то свойства

2019-03-13 11:07 UTC, rmbaad commented on src/style.css
> +    width: 20%;
Этот класс дублирует почти полностью класс sender. Можно в него внести только различающиеся свойства и в html задать где нужно два класса <div class="sender sender_read">

2019-03-13 11:07 UTC, rmbaad commented on src/style.css
> +    text-indent: 30px;
Не всем параграфам на странице могут понадобиться подобные стили

2019-03-13 11:07 UTC, rmbaad commented on src/style.css
> +    float: right;
То же самое. Это сломает все остальные картинки

2019-03-13 11:07 UTC, rmbaad commented on src/style.css
> +    position: absolute;
Единственное место где оправдан position absolute в рамках текущего задания

2019-03-13 11:07 UTC, rmbaad commented on src/style.css
> +.info_option {
Эти пункты не должны ужиматься и сокращаться по тексту, пользователь не сможет увидеть что в них

2019-03-13 11:07 UTC, rmbaad commented on src/index.html
> +                        <div id="incoming" class="option">Входящие</div>
Правильнее сделать это списком (например ul)

2019-03-13 11:07 UTC, rmbaad commented on src/index.html
> +                        <div class="option">Отправленные</div>
Нет ссылок в меню

2019-03-13 11:07 UTC, rmbaad commented on src/index.html
> +                                <p>
Обтекание не по заданию. Форма не должна быть квадратной

2019-03-13 11:09 UTC, rmbaad requested changes

2019-03-13 11:09 UTC, rmbaad commented on src/index.html
> +                    <div id="yandex">Яндекс</div>
Логотип не как в макете

2019-03-13 11:10 UTC, rmbaad commented on src/style.css
> +    position: absolute;
Но выглядит в итоге футер не как в макете

2019-03-16 17:12 UTC, teremax commented
@rmbaad, замечания исправлены.

2019-03-18 08:32 UTC, rmbaad requested changes

2019-03-18 08:32 UTC, rmbaad commented on src/index.html
> +                    <div class="letters=">
Если писем сделать больше, футер начинает перекрывать письма. Одно из условий задания — чтобы не зависимо от кол-ва данных всё работало как надо

2019-03-18 08:32 UTC, rmbaad commented on src/style.css
> +    position: absolute;
Всё ещё расположение на асболютах. Такого быть не должно

2019-03-18 08:32 UTC, rmbaad commented on src/index.html
> +                            <div class="info_option">Помощь и обратная связь</div>
Должны быть ссылки

2019-03-22 19:03 UTC, teremax commented
@rmbaad, еще один набор замечаний исправлен.
P.s. основная мотивация position: absolute была в том, чтобы "контент" не ехал при уменьшении размера окна. Другим такое засчитывали (и гораздо хуже вещи прощали, если вы посмотрите на некоторые другие работы), но вы проверяете строже. Это, конечно, круто - я больше узнаю, больше научусь, но получать "half-accepted" при этом не очень радует.

2019-03-25 16:58 UTC, rmbaad commented
Дело в том, что при position absolute как раз всё будет ехать и налезать друг на друга, ну или оставаться "деревянным" и не тянуться как надо. Position absolute это дурной тон, плохая поддержка (об этом говорили на лекции) и использование технологии не по назначению.
Мы к сожалению не можем следить за всеми работами, каждый проверяет так, как считает нужным, опираясь на наши общие принципы и условия.
Не переживай, у тебя хорошие результаты. Делай вовремя, вникай в суть, и всё будет хорошо)

2019-03-25 16:58 UTC, closed without merging