Шушарин Дмитрий, М3337 task2
itmo2019/task2 pull request #9
Opened 2019-03-09 10:17 UTC by Top1Miami

2019-03-18 05:55 UTC, trixartem requested changes
Есть замечания по верстке:
- У меню слева маленькие вертикальные отступы, нет эффекта при наведении
- Синий кружок, который обозначает, что письмо не прочтенное, должен быть рядом с логотипом
- Если сжать экран, то блок с письмами перескакивает на другую строку
- Если в теле письма много текста, то блок перекрывает подвал
- Картинка не обтекается по кругу текстом

2019-03-18 05:55 UTC, trixartem commented on task2.html
> +        <svg class="logo" viewBox="0 0 77 31"><title xmlns="http://www.w3.org/2000/svg">Artboard 3</title>
Что бы не было мусора в коде, картинку лучше вынести в файл и загружать

2019-03-18 05:55 UTC, trixartem commented on task2.html
> +        <div class="stripe">
Можно сделать одним элементом чере before и after

2019-03-18 05:55 UTC, trixartem commented on task2.html
> +    <title>Title</title>
Нет заголовка(

2019-03-18 05:55 UTC, trixartem commented on task2.html
> +                <li class="leftList"><a href="#" class = "leftLinks">Отправленные</a></li>
А почему остальные не ссылки?
При наведении тоже должен быть эффект

2019-03-18 05:55 UTC, trixartem commented on task2.html
> +                    <div class="manulText">
Если здесь будет много текста, то блок перекроет footer

2019-03-18 05:55 UTC, trixartem commented on task2.html
> +                    <div class="manulText">
В тексте не хватет тегов, например p

2019-03-18 05:55 UTC, trixartem commented on style.css
> +    /*margin-top: 19em;*/
Комменты можно убрать

2019-03-18 05:55 UTC, trixartem commented on style.css
> +    src: url("HelveticaNeueCyr-Medium.woff");
Надо добавить системный шрифт, вдруг он установлен у пользователя

2019-03-18 05:55 UTC, trixartem commented on style.css
> +    background-color: white;
#fff

2019-03-18 05:55 UTC, trixartem commented on style.css
> +.manulImgCirc {
Картинка не обтекается по кругу

2019-03-18 05:55 UTC, trixartem commented on style.css
> +    font-family: "Helvetica Neue", sans-serif;
font-size, font-family можно схлопнуть в одно свойство

2019-03-18 05:55 UTC, trixartem commented on style.css
> +    margin-left: 20%;
Почему 20%, а не PX?

2019-03-18 05:55 UTC, trixartem commented on style.css
> +    background-color: #000000;
Можно сократить до #000

2019-03-18 06:48 UTC, Top1Miami commented
А как сделать чтобы, окошко не уползало влево, как сказать ему что пусть берет все возможное пространство справо от кнопок

2019-03-18 06:52 UTC, Top1Miami commented on task2.html
> +                    <div class="manulText">
А если футеру z index сделать больше чем у текста норм?

2019-03-18 10:51 UTC, Top1Miami commented on task2.html
> +        <svg class="logo" viewBox="0 0 77 31"><title xmlns="http://www.w3.org/2000/svg">Artboard 3</title>
Но их же нет в общем доступе, скрин что ли сделать?

2019-03-20 05:43 UTC, trixartem requested changes
- Если добавить много писем, то они выпадывают за пределы блока.
- Если добавить в письмо много текст, то перекрывается подвал
- Надо попроавить немного разметку
```
|       Шапка       |
–––––––––––––––––––––
|Левая | Правая     |
|      |            |
|      |            |
|150px | оставшееся |
|      | место      |
|      |            |
```

2019-03-20 05:43 UTC, trixartem commented on task2.html
> +        <svg class="logo" viewBox="0 0 77 31"><title xmlns="http://www.w3.org/2000/svg">Artboard 3</title>
Можно скачать файлом и положить рядом

2019-03-20 05:43 UTC, trixartem commented on task2.html
> +            <li class="messageBoxList">
Лучше сделать отдельным элементом - шапкой, потому что это семантически не верно.

2019-03-20 05:43 UTC, trixartem commented on task2.html
> +                        Манул — животное размером с домашнюю кошку: длина его тела 52—65 см, хвоста 23—31 см; весит он
Не хватает разбивки на параграфы, хотя видно что разбивал переносами строк, но отображается все как один сплошной текст

2019-03-20 05:43 UTC, trixartem commented on task2.html
> +                    <div class="read">Соберите всю почту в этот ящик asddddddddasdasdasdasdasdasasdasdsadddddddddddddddddddddd</div>
Для красоты, лучше что бы текст обрезался и в конце выставлялись "..."

2019-03-20 05:43 UTC, trixartem commented on style.css
> +.stripe {
Можно сделать одним элементом через before after

2019-03-20 05:43 UTC, trixartem commented on style.css
> +    width: max-content;
Лучше использовать фиксированный размер, так очевиднее какой размер примет инпут

2019-03-20 05:43 UTC, trixartem commented on style.css
> +    border: none;
border: 0

2019-03-25 17:12 UTC, closed without merging